/*
 * Copyright (C) 2025 Alberto Irurueta Carro (alberto@irurueta.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.irurueta.android.navigation.inertial.calibration.intervals.measurements

import com.irurueta.android.navigation.inertial.collectors.measurements.AccelerometerSensorMeasurement
import com.irurueta.navigation.inertial.BodyKinematics
import com.irurueta.navigation.inertial.calibration.AccelerationTriad
import com.irurueta.navigation.inertial.calibration.StandardDeviationBodyKinematics
import com.irurueta.navigation.inertial.calibration.generators.AccelerometerMeasurementsGenerator
import com.irurueta.navigation.inertial.calibration.generators.AccelerometerMeasurementsGeneratorListener
import com.irurueta.navigation.inertial.calibration.intervals.TriadStaticIntervalDetector

/**
 * Generates measurements that can later be used by accelerometer calibrators.
 * Measurements are generated by taking into account static and dynamic intervals on the device,
 * when the device is kept static (e.g. motionless), or when some force is applied to the device
 * changing its position or orientation.
 * Measurement generator converts device ENU measurements into measurements expressed in local
 * tangent plane NED coordinates.
 *
 * @param initializationStartedListener listener to notify when initialization starts.
 * @property initializationCompletedListener listener to notify when initialization successfully
 * completes.
 * @property errorListener listener to notify errors.
 * @property staticIntervalDetectedListener listener to notify when a static interval is detected.
 * @property dynamicIntervalDetectedListener listener to notify when a dynamic interval is detected.
 * @property staticIntervalSkippedListener listener to notify when a static interval is skipped if
 * its duration is too short.
 * @property dynamicIntervalSkippedListener listener to notify when a dynamic interval is skipped if
 * its duration is too long.
 * @property generatedMeasurementListener listener to notify when a new calibration measurement is
 * generated.
 * @property resetListener listener to notify when generator is restarted.
 */
class AccelerometerMeasurementGeneratorProcessor(
    initializationStartedListener: OnInitializationStartedListener<AccelerometerMeasurementGeneratorProcessor>? = null,
    initializationCompletedListener: OnInitializationCompletedListener<AccelerometerMeasurementGeneratorProcessor>? = null,
    errorListener: OnErrorListener<AccelerometerMeasurementGeneratorProcessor>? = null,
    staticIntervalDetectedListener: OnStaticIntervalDetectedListener<AccelerometerMeasurementGeneratorProcessor>? = null,
    dynamicIntervalDetectedListener: OnDynamicIntervalDetectedListener<AccelerometerMeasurementGeneratorProcessor>? = null,
    staticIntervalSkippedListener: OnStaticIntervalSkippedListener<AccelerometerMeasurementGeneratorProcessor>? = null,
    dynamicIntervalSkippedListener: OnDynamicIntervalSkippedListener<AccelerometerMeasurementGeneratorProcessor>? = null,
    generatedMeasurementListener: OnGeneratedMeasurementListener<AccelerometerMeasurementGeneratorProcessor, StandardDeviationBodyKinematics>? = null,
    resetListener: OnResetListener<AccelerometerMeasurementGeneratorProcessor>? = null
) : SingleSensorCalibrationMeasurementGeneratorProcessor<
            AccelerometerMeasurementGeneratorProcessor,
            StandardDeviationBodyKinematics,
            AccelerometerMeasurementsGenerator,
            AccelerometerMeasurementsGeneratorListener,
            BodyKinematics>(
                initializationStartedListener,
                initializationCompletedListener,
                errorListener,
                staticIntervalDetectedListener,
                dynamicIntervalDetectedListener,
                staticIntervalSkippedListener,
                dynamicIntervalSkippedListener,
                generatedMeasurementListener,
                resetListener
            ) {

    /**
     * Listener for internal measurement generator.
     */
    override val measurementsGeneratorListener =
        object : AccelerometerMeasurementsGeneratorListener {
            override fun onInitializationStarted(generator: AccelerometerMeasurementsGenerator?) {
                initializationStartedListener?.onInitializationStarted(
                    this@AccelerometerMeasurementGeneratorProcessor
                )
            }

            override fun onInitializationCompleted(
                generator: AccelerometerMeasurementsGenerator?,
                baseNoiseLevel: Double
            ) {
                initializationCompletedListener?.onInitializationCompleted(
                    this@AccelerometerMeasurementGeneratorProcessor,
                    baseNoiseLevel
                )
            }

            override fun onError(
                generator: AccelerometerMeasurementsGenerator?,
                reason: TriadStaticIntervalDetector.ErrorReason
            ) {
                errorListener?.onError(
                    this@AccelerometerMeasurementGeneratorProcessor,
                    mapErrorReason(reason)
                )
            }

            override fun onStaticIntervalDetected(generator: AccelerometerMeasurementsGenerator?) {
                staticIntervalDetectedListener?.onStaticIntervalDetected(
                    this@AccelerometerMeasurementGeneratorProcessor
                )
            }

            override fun onDynamicIntervalDetected(generator: AccelerometerMeasurementsGenerator?) {
                dynamicIntervalDetectedListener?.onDynamicIntervalDetected(
                    this@AccelerometerMeasurementGeneratorProcessor
                )
            }

            override fun onStaticIntervalSkipped(generator: AccelerometerMeasurementsGenerator?) {
                staticIntervalSkippedListener?.onStaticIntervalSkipped(
                    this@AccelerometerMeasurementGeneratorProcessor
                )
            }

            override fun onDynamicIntervalSkipped(generator: AccelerometerMeasurementsGenerator?) {
                dynamicIntervalSkippedListener?.onDynamicIntervalSkipped(
                    this@AccelerometerMeasurementGeneratorProcessor
                )
            }

            override fun onGeneratedMeasurement(
                generator: AccelerometerMeasurementsGenerator?,
                measurement: StandardDeviationBodyKinematics
            ) {
                generatedMeasurementListener?.onGeneratedMeasurement(
                    this@AccelerometerMeasurementGeneratorProcessor,
                    measurement
                )
            }

            override fun onReset(generator: AccelerometerMeasurementsGenerator?) {
                resetListener?.onReset(this@AccelerometerMeasurementGeneratorProcessor)
            }
        }

    /**
     * Internal measurements generator for accelerometer calibration.
     */
    override val measurementsGenerator =
        AccelerometerMeasurementsGenerator(measurementsGeneratorListener)

    /**
     * Body kinematics used by internal measurement generator.
     * For accelerometer calibration purposes, only specific force is required.
     */
    override val sample = BodyKinematics()

    /**
     * Accelerometer sensor measurement expressed in NED coordinates.
     */
    private val nedMeasurement = AccelerometerSensorMeasurement()

    /**
     * Acceleration triad.
     */
    private val accelerationTriad = AccelerationTriad()

    /**
     * Processes an accelerometer measurement to generate an instance of type [BodyKinematics] to be
     * used by the internal measurement generator.
     * Since [AccelerometerMeasurementsGenerator] only requires acceleration information, no data is
     * provided for angular rates in processed result.
     *
     * @param measurement accelerometer sensor measurement.
     */
    override fun processAccelerometerData(
        measurement: AccelerometerSensorMeasurement,
        diffSeconds: Double,
        result: BodyKinematics
    ) {
        // convert from device ENU coordinates to local plane NED coordinates
        measurement.toNed(nedMeasurement)
        // convert to triad taking into account measurement bias if available
        nedMeasurement.toTriad(accelerationTriad)

        result.specificForceTriad = accelerationTriad
    }
}