/*
 * Copyright (C) 2025 Alberto Irurueta Carro (alberto@irurueta.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.irurueta.android.navigation.inertial.calibration.intervals.measurements

import android.content.Context
import com.irurueta.android.navigation.inertial.collectors.SensorDelay
import com.irurueta.android.navigation.inertial.collectors.measurements.AccelerometerSensorType
import com.irurueta.navigation.inertial.BodyKinematics
import com.irurueta.navigation.inertial.calibration.StandardDeviationBodyKinematics
import com.irurueta.navigation.inertial.calibration.generators.AccelerometerMeasurementsGenerator
import com.irurueta.navigation.inertial.calibration.generators.AccelerometerMeasurementsGeneratorListener

/**
 * Generates measurements that can later be used by accelerometer calibrators.
 * Measurements are generated by taking into account static and dynamic intervals on the device,
 * when the device is kept static (e.g. motionless), or when some force is applied to the device
 * changing its position or orientation.
 * Measurement generator converts device ENU measurements into measurements expressed in local
 * tangent plane NED coordinates.
 *
 * @property context Android context.
 * @property accelerometerSensorType One of the supported accelerometer sensor types.
 * @property accelerometerSensorDelay Delay of sensor between samples.
 * @property initializationStartedListener listener to notify when initialization starts.
 * @property initializationCompletedListener listener to notify when initialization successfully
 * completes.
 * @property errorListener listener to notify errors.
 * @property staticIntervalDetectedListener listener to notify when a static interval is detected.
 * @property dynamicIntervalDetectedListener listener to notify when a dynamic interval is detected.
 * @property staticIntervalSkippedListener listener to notify when a static interval is skipped if
 * its duration is too short.
 * @property dynamicIntervalSkippedListener listener to notify when a dynamic interval is skipped if
 * its duration is too long.
 * @property generatedMeasurementListener listener to notify when a new calibration measurement is
 * generated.
 * @property resetListener listener to notify when generator is restarted.
 */
class AccelerometerMeasurementGenerator(
    context: Context,
    accelerometerSensorType: AccelerometerSensorType =
        AccelerometerSensorType.ACCELEROMETER_UNCALIBRATED,
    accelerometerSensorDelay: SensorDelay = SensorDelay.FASTEST,
    initializationStartedListener: OnInitializationStartedListener<AccelerometerMeasurementGenerator>? = null,
    initializationCompletedListener: OnInitializationCompletedListener<AccelerometerMeasurementGenerator>? = null,
    errorListener: OnErrorListener<AccelerometerMeasurementGenerator>? = null,
    staticIntervalDetectedListener: OnStaticIntervalDetectedListener<AccelerometerMeasurementGenerator>? = null,
    dynamicIntervalDetectedListener: OnDynamicIntervalDetectedListener<AccelerometerMeasurementGenerator>? = null,
    staticIntervalSkippedListener: OnStaticIntervalSkippedListener<AccelerometerMeasurementGenerator>? = null,
    dynamicIntervalSkippedListener: OnDynamicIntervalSkippedListener<AccelerometerMeasurementGenerator>? = null,
    generatedMeasurementListener: OnGeneratedMeasurementListener<AccelerometerMeasurementGenerator, StandardDeviationBodyKinematics>? = null,
    resetListener: OnResetListener<AccelerometerMeasurementGenerator>? = null
) : SingleSensorCalibrationMeasurementGenerator<
        AccelerometerMeasurementGenerator,
        AccelerometerMeasurementGeneratorProcessor,
        StandardDeviationBodyKinematics,
        AccelerometerMeasurementsGenerator,
        AccelerometerMeasurementsGeneratorListener,
        BodyKinematics>(
    context,
    accelerometerSensorType,
    accelerometerSensorDelay,
    initializationStartedListener,
    initializationCompletedListener,
    errorListener,
    staticIntervalDetectedListener,
    dynamicIntervalDetectedListener,
    staticIntervalSkippedListener,
    dynamicIntervalSkippedListener,
    generatedMeasurementListener,
    resetListener
) {
    /**
     * Internal processor to process accelerometer sensor measurements.
     */
    override val processor = AccelerometerMeasurementGeneratorProcessor(
        initializationStartedListener = { _ ->
            initializationStartedListener?.onInitializationStarted(
                this
            )
        },
        initializationCompletedListener = { _, baseNoiseLevel ->
            initializationCompletedListener?.onInitializationCompleted(
                this,
                baseNoiseLevel
            )
        },
        errorListener = { _, reason -> errorListener?.onError(this, reason) },
        staticIntervalDetectedListener = { _ ->
            staticIntervalDetectedListener?.onStaticIntervalDetected(
                this
            )
        },
        dynamicIntervalDetectedListener = { _ ->
            dynamicIntervalDetectedListener?.onDynamicIntervalDetected(
                this
            )
        },
        staticIntervalSkippedListener = { _ ->
            staticIntervalSkippedListener?.onStaticIntervalSkipped(
                this
            )
        },
        dynamicIntervalSkippedListener = { _ ->
            dynamicIntervalSkippedListener?.onDynamicIntervalSkipped(
                this
            )
        },
        generatedMeasurementListener = { _, measurement ->
            generatedMeasurementListener?.onGeneratedMeasurement(
                this,
                measurement
            )
        },
        resetListener = { _ -> resetListener?.onReset(this) }
    )
}