/*
 * Copyright (C) 2025 Alberto Irurueta Carro (alberto@irurueta.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.irurueta.android.navigation.inertial.calibration.intervals.measurements

import com.irurueta.android.navigation.inertial.calibration.intervals.ErrorReason
import com.irurueta.android.navigation.inertial.calibration.intervals.Status
import com.irurueta.android.navigation.inertial.collectors.measurements.AccelerometerSensorMeasurement
import com.irurueta.android.navigation.inertial.collectors.measurements.GyroscopeSensorMeasurement
import com.irurueta.android.navigation.inertial.collectors.measurements.MagnetometerSensorMeasurement
import com.irurueta.navigation.inertial.BodyKinematics
import com.irurueta.navigation.inertial.BodyMagneticFluxDensity
import com.irurueta.navigation.inertial.calibration.AccelerationTriad
import com.irurueta.navigation.inertial.calibration.AngularSpeedTriad
import com.irurueta.navigation.inertial.calibration.BodyKinematicsSequence
import com.irurueta.navigation.inertial.calibration.MagneticFluxDensityTriad
import com.irurueta.navigation.inertial.calibration.StandardDeviationBodyKinematics
import com.irurueta.navigation.inertial.calibration.StandardDeviationBodyMagneticFluxDensity
import com.irurueta.navigation.inertial.calibration.StandardDeviationTimedBodyKinematics
import com.irurueta.navigation.inertial.calibration.TimedBodyKinematicsAndMagneticFluxDensity
import com.irurueta.navigation.inertial.calibration.generators.AccelerometerGyroscopeAndMagnetometerMeasurementsGenerator
import com.irurueta.navigation.inertial.calibration.generators.AccelerometerGyroscopeAndMagnetometerMeasurementsGeneratorListener
import com.irurueta.navigation.inertial.calibration.generators.AccelerometerMeasurementsGenerator
import com.irurueta.navigation.inertial.calibration.intervals.TriadStaticIntervalDetector
import com.irurueta.navigation.inertial.calibration.noise.AccumulatedAngularSpeedTriadNoiseEstimator
import com.irurueta.navigation.inertial.calibration.noise.AccumulatedMagneticFluxDensityTriadNoiseEstimator
import com.irurueta.units.Acceleration
import com.irurueta.units.AngularSpeed
import com.irurueta.units.AngularSpeedUnit
import com.irurueta.units.MagneticFluxDensity
import com.irurueta.units.MagneticFluxDensityUnit

/**
 * Generates measurements that can later be used by accelerometer, gyroscope and magnetometer
 * calibrators.
 * Measurements are generated by taking into account static and dynamic intervals on the device,
 * when the device is kept static (e.g. motionless), or when some force is applied to the device
 * changing its position or orientation.
 * Static and dynamic intervals are always measured using the accelerometer.
 * Additionally, the gyroscope and magnetometer are also used, and measurements are generated to
 * calibrate accelerometers, gyroscopes and magnetometers.
 * Measurement generator converts device ENU measurements into measurements expressed in local
 * tangent plane NED coordinates.
 *
 * @param initializationStartedListener listener to notify when initialization starts.
 * @property initializationCompletedListener listener to notify when initialization successfully
 * completes.
 * @property errorListener listener to notify errors.
 * @property staticIntervalDetectedListener listener to notify when a static interval is detected.
 * @property dynamicIntervalDetectedListener listener to notify when a dynamic interval is detected.
 * @property staticIntervalSkippedListener listener to notify when a static interval is skipped if
 * its duration is too short.
 * @property dynamicIntervalSkippedListener listener to notify when a dynamic interval is skipped if
 * its duration is too long.
 * @property generatedAccelerometerMeasurementListener listener to notify when a new accelerometer
 * calibration measurement is generated.
 * @property generatedGyroscopeMeasurementListener listener to notify when a new gyroscope
 * calibration measurement is generated.
 * @property generatedMagnetometerMeasurementListener listener to notify when a new magnetometer
 * calibration measurement is generated.
 * @property resetListener listener to notify when generator is restarted.
 */
class AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor(
    var initializationStartedListener: OnInitializationStartedListener? = null,
    var initializationCompletedListener: OnInitializationCompletedListener? = null,
    var errorListener: OnErrorListener? = null,
    var staticIntervalDetectedListener: OnStaticIntervalDetectedListener? = null,
    var dynamicIntervalDetectedListener: OnDynamicIntervalDetectedListener? = null,
    var staticIntervalSkippedListener: OnStaticIntervalSkippedListener? = null,
    var dynamicIntervalSkippedListener: OnDynamicIntervalSkippedListener? = null,
    var generatedAccelerometerMeasurementListener: OnGeneratedAccelerometerMeasurementListener? = null,
    var generatedGyroscopeMeasurementListener: OnGeneratedGyroscopeMeasurementListener? = null,
    var generatedMagnetometerMeasurementListener: OnGeneratedMagnetometerMeasurementListener? = null,
    var resetListener: OnResetListener? = null
) : CalibrationMeasurementGeneratorProcessor<TimedBodyKinematicsAndMagneticFluxDensity>() {

    /**
     * Listener for internal measurement generator.
     */
    private val measurementsGeneratorListener = object :
        AccelerometerGyroscopeAndMagnetometerMeasurementsGeneratorListener {
        override fun onInitializationStarted(generator: AccelerometerGyroscopeAndMagnetometerMeasurementsGenerator?) {
            initializationStartedListener?.onInitializationStarted(
                this@AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor
            )
        }

        override fun onInitializationCompleted(
            generator: AccelerometerGyroscopeAndMagnetometerMeasurementsGenerator?,
            accelerometerBaseNoiseLevel: Double
        ) {
            initializationCompletedListener?.onInitializationCompleted(
                this@AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor,
                accelerometerBaseNoiseLevel
            )
        }

        override fun onError(
            generator: AccelerometerGyroscopeAndMagnetometerMeasurementsGenerator?,
            reason: TriadStaticIntervalDetector.ErrorReason
        ) {
            errorListener?.onError(
                this@AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor,
                mapErrorReason(reason)
            )
        }

        override fun onStaticIntervalDetected(generator: AccelerometerGyroscopeAndMagnetometerMeasurementsGenerator?) {
            staticIntervalDetectedListener?.onStaticIntervalDetected(
                this@AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor
            )
        }

        override fun onDynamicIntervalDetected(generator: AccelerometerGyroscopeAndMagnetometerMeasurementsGenerator?) {
            dynamicIntervalDetectedListener?.onDynamicIntervalDetected(
                this@AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor
            )
        }

        override fun onStaticIntervalSkipped(generator: AccelerometerGyroscopeAndMagnetometerMeasurementsGenerator?) {
            staticIntervalSkippedListener?.onStaticIntervalSkipped(
                this@AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor
            )
        }

        override fun onDynamicIntervalSkipped(generator: AccelerometerGyroscopeAndMagnetometerMeasurementsGenerator?) {
            dynamicIntervalSkippedListener?.onDynamicIntervalSkipped(
                this@AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor
            )
        }

        override fun onGeneratedAccelerometerMeasurement(
            generator: AccelerometerGyroscopeAndMagnetometerMeasurementsGenerator?,
            measurement: StandardDeviationBodyKinematics
        ) {
            generatedAccelerometerMeasurementListener?.onGeneratedAccelerometerMeasurement(
                this@AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor,
                measurement
            )
        }

        override fun onGeneratedGyroscopeMeasurement(
            generator: AccelerometerGyroscopeAndMagnetometerMeasurementsGenerator?,
            measurement: BodyKinematicsSequence<StandardDeviationTimedBodyKinematics>
        ) {
            generatedGyroscopeMeasurementListener?.onGeneratedGyroscopeMeasurement(
                this@AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor,
                measurement
            )
        }

        override fun onGeneratedMagnetometerMeasurement(
            generator: AccelerometerGyroscopeAndMagnetometerMeasurementsGenerator?,
            measurement: StandardDeviationBodyMagneticFluxDensity
        ) {
            generatedMagnetometerMeasurementListener?.onGeneratedMagnetometerMeasurement(
                this@AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor,
                measurement
            )
        }

        override fun onReset(generator: AccelerometerGyroscopeAndMagnetometerMeasurementsGenerator?) {
            resetListener?.onReset(this@AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor)
        }
    }

    /**
     * Internal measurements generator for accelerometer, gyroscope and magnetometer calibration.
     */
    private val measurementsGenerator =
        AccelerometerGyroscopeAndMagnetometerMeasurementsGenerator(measurementsGeneratorListener)

    /**
     * Gets or sets minimum number of samples required in a static interval to be taken into
     * account. Smaller static intervals will be discarded.
     *
     * @throws IllegalArgumentException if provided value is less than 2.
     */
    override var minStaticSamples: Int
        get() = measurementsGenerator.minStaticSamples
        @Throws(IllegalArgumentException::class)
        set(value) {
            measurementsGenerator.minStaticSamples = value
        }

    /**
     * Gets or sets maximum number of samples allowed in dynamic intervals.
     * Dynamic intervals exceeding this value are discarded.
     *
     * @throws IllegalArgumentException if provided value is less than 2.
     */
    override var maxDynamicSamples: Int
        get() = measurementsGenerator.maxDynamicSamples
        @Throws(IllegalArgumentException::class)
        set(value) {
            measurementsGenerator.maxDynamicSamples = value
        }

    /**
     * Gets or sets length of number of samples to keep within the window being processed to
     * determine instantaneous sensor noise level. Window size must always be larger than
     * allowed minimum value, which is 2 and must have an odd value.
     *
     * @throws IllegalArgumentException if provided value is not valid.
     */
    override var windowSize: Int
        get() = measurementsGenerator.windowSize
        @Throws(IllegalArgumentException::class)
        set(value) {
            measurementsGenerator.windowSize = value
        }

    /**
     * Gets or sets number of samples to be processed initially while keeping the sensor static in
     * order to find the base noise level when device is static.
     *
     * @throws IllegalArgumentException if provided value is less than
     * [TriadStaticIntervalDetector.MINIMUM_INITIAL_STATIC_SAMPLES].
     */
    override var initialStaticSamples: Int
        get() = measurementsGenerator.initialStaticSamples
        @Throws(IllegalArgumentException::class)
        set(value) {
            measurementsGenerator.initialStaticSamples = value
        }

    /**
     * Gets or sets factor to be applied to detected base noise level in order to determine
     * threshold for static/dynamic period changes. This factor is unit-less.
     *
     * @throws IllegalArgumentException if provided value is zero or negative
     */
    override var thresholdFactor: Double
        get() = measurementsGenerator.thresholdFactor
        @Throws(IllegalArgumentException::class)
        set(value) {
            measurementsGenerator.thresholdFactor = value
        }

    /**
     * Gets or sets factor to determine that a sudden movement has occurred during initialization if
     * instantaneous noise level exceeds accumulated noise level by this factor amount. This factor
     * is unit-less.
     *
     * @throws IllegalArgumentException if provided value is zero or negative.
     */
    override var instantaneousNoiseLevelFactor: Double
        get() = measurementsGenerator.instantaneousNoiseLevelFactor
        @Throws(IllegalArgumentException::class)
        set(value) {
            measurementsGenerator.instantaneousNoiseLevelFactor = value
        }

    /**
     * Gets or sets overall absolute threshold to determine whether there has been excessive motion
     * during the whole initialization phase. Failure will be detected if estimated base noise level
     * exceeds this threshold when initialization completes. This threshold is expressed in meters
     * per squared second (m/s^2).
     *
     * @throws IllegalArgumentException if provided value is zero or negative.
     */
    override var baseNoiseLevelAbsoluteThreshold: Double
        get() = measurementsGenerator.baseNoiseLevelAbsoluteThreshold
        @Throws(IllegalArgumentException::class)
        set(value) {
            measurementsGenerator.baseNoiseLevelAbsoluteThreshold = value
        }

    /**
     * Gets or sets overall absolute threshold to determine whether there has been excessive motion
     * during the whole initialization phase. Failure will be detected if estimated base noise level
     * exceeds this threshold when initialization completes.
     *
     * @throws IllegalArgumentException if provided value is zero or negative.
     * @throws IllegalStateException if detector is currently running.
     */
    override var baseNoiseLevelAbsoluteThresholdAsMeasurement: Acceleration
        get() = measurementsGenerator.baseNoiseLevelAbsoluteThresholdAsMeasurement
        @Throws(IllegalArgumentException::class)
        set(value) {
            measurementsGenerator.setBaseNoiseLevelAbsoluteThreshold(value)
        }

    /**
     * Gets overall absolute threshold to determine whether there has been excessive motion during
     * the whole initialization phase. Failure will be detected if estimated base noise level
     * exceeds this threshold when initialization completes.
     *
     * @param result instance where result will be stored.
     */
    override fun getBaseNoiseLevelAbsoluteThresholdAsMeasurement(result: Acceleration) {
        measurementsGenerator.getBaseNoiseLevelAbsoluteThresholdAsMeasurement(result)
    }

    /**
     * Gets accelerometer measurement base noise level that has been detected during initialization
     * expressed in meters per squared second (m/s^2).
     * This is only available once detector completes initialization.
     */
    override val accelerometerBaseNoiseLevel: Double?
        get() = if (initialized) {
            measurementsGenerator.accelerometerBaseNoiseLevel
        } else {
            null
        }

    /**
     * Gets sensor measurement base noise level that has been detected during initialization.
     * This is only available once detector completes initialization.
     */
    override val accelerometerBaseNoiseLevelAsMeasurement: Acceleration?
        get() = if (initialized) {
            measurementsGenerator.accelerometerBaseNoiseLevelAsMeasurement
        } else {
            null
        }

    /**
     * Gets sensor measurement base noise level that has been detected during initialization.
     * This is only available once detector completes initialization.
     *
     * @param result instance where result will be stored.
     * @return true if result is available, false otherwise.
     */
    override fun getAccelerometerBaseNoiseLevelAsMeasurement(result: Acceleration): Boolean {
        return if (initialized) {
            measurementsGenerator.getAccelerometerBaseNoiseLevelAsMeasurement(result)
            true
        } else {
            false
        }
    }

    /**
     * Gets measurement base noise level PSD (Power Spectral Density) expressed in (m^2 * s^-3).
     */
    override val accelerometerBaseNoiseLevelPsd: Double?
        get() = if (initialized) {
            measurementsGenerator.accelerometerBaseNoiseLevelPsd
        } else {
            null
        }

    /**
     * Gets measurement base noise level root PSD (Power Spectral Density) expressed
     * in (m * s^-1.5).
     * This is only available once detector completes initialization.
     */
    override val accelerometerBaseNoiseLevelRootPsd: Double?
        get() = if (initialized) {
            measurementsGenerator.accelerometerBaseNoiseLevelRootPsd
        } else {
            null
        }

    /**
     * Gets estimated threshold to determine static/dynamic period changes expressed in meters per
     * squared second (m/s^2).
     * This is only available once detector completes initialization.
     */
    override val threshold: Double?
        get() = if (initialized) {
            measurementsGenerator.threshold
        } else {
            null
        }

    /**
     * Gets estimated threshold to determine static/dynamic period changes.
     * This is only available once detector completes initialization.
     */
    override val thresholdAsMeasurement: Acceleration?
        get() = if (initialized) {
            measurementsGenerator.thresholdAsMeasurement
        } else {
            null
        }

    /**
     * Gets estimated threshold to determine static/dynamic period changes.
     * This is only available once detector completes initialization.
     *
     * @param result instance where result will be stored.
     * @return true if result is available, false otherwise.
     */
    override fun getThresholdAsMeasurement(result: Acceleration): Boolean {
        return if (initialized) {
            measurementsGenerator.getThresholdAsMeasurement(result)
            true
        } else {
            false
        }
    }

    /**
     * Gets number of samples that have been processed in a static period so far.
     */
    override val processedStaticSamples: Int
        get() = measurementsGenerator.processedStaticSamples

    /**
     * Gets number of samples that have been processed in a dynamic period so far.
     */
    override val processedDynamicSamples: Int
        get() = measurementsGenerator.processedDynamicSamples

    /**
     * Indicates whether last static interval must be skipped.
     */
    override val isStaticIntervalSkipped: Boolean
        get() = measurementsGenerator.isStaticIntervalSkipped

    /**
     * Indicates whether last dynamic interval must be skipped.
     */
    override val isDynamicIntervalSkipped: Boolean
        get() = measurementsGenerator.isDynamicIntervalSkipped

    /**
     * Gets status of measurement generator.
     * Initially the generator will be idle.
     * Once it starts, it will start the initialization phase, and once
     * initialization is complete, it will switch between static or dynamic interval
     * until generator is stopped or an error occurs.
     */
    override val status: Status
        get() = Status.mapStatus(measurementsGenerator.status, unreliable)

    /**
     * Number of gyroscope measurements that have been processed.
     */
    var numberOfProcessedGyroscopeMeasurements: Int = 0
        private set

    /**
     * Gets gyroscope measurement base noise level that has been detected during initialization
     * expressed in radians per second (rad/s).
     * This is only available once generator completes initialization.
     */
    var gyroscopeBaseNoiseLevel: Double? = null
        private set

    /**
     * Gets gyroscope measurement base noise level that has been detected during initialization.
     * This is only available once generator completes initialization.
     */
    val gyroscopeBaseNoiseLevelAsMeasurement: AngularSpeed?
        get() {
            val value = gyroscopeBaseNoiseLevel ?: return null
            return AngularSpeed(value, AngularSpeedUnit.RADIANS_PER_SECOND)
        }

    /**
     * Gets gyroscope measurement base noise level that has been detected during initialization.
     * This is only available once generator completes initialization.
     *
     * @param result instance where result will be stored.
     * @return true if result is available, false otherwise.
     */
    fun getGyroscopeBaseNoiseLevelAsMeasurement(result: AngularSpeed): Boolean {
        val value = gyroscopeBaseNoiseLevel ?: return false
        result.value = value
        result.unit = AngularSpeedUnit.RADIANS_PER_SECOND
        return true
    }

    /**
     * Number of magnetometer measurements that have been processed.
     */
    var numberOfProcessedMagnetometerMeasurements: Int = 0
        private set

    /**
     * Gets magnetometer measurement base noise level that has been detected during initialization
     * expressed in Teslas (T).
     * This is only available once generator completes initialization.
     */
    var magnetometerBaseNoiseLevel: Double? = null
        private set

    /**
     * Gets magnetometer measurement base noise level that has been detected during initialization.
     * This is only available once generator completes initialization.
     */
    val magnetometerBaseNoiseLevelAsMeasurement: MagneticFluxDensity?
        get() {
            val value = magnetometerBaseNoiseLevel ?: return null
            return MagneticFluxDensity(value, MagneticFluxDensityUnit.TESLA)
        }

    /**
     * Gets magnetometer measurement base noise level that has been detected during initialization.
     * This is only available once generator completes initialization.
     *
     * @param result instance where result will be stored.
     * @return true if result is available, false otherwise.
     */
    fun getMagnetometerBaseNoiseLevelAsMeasurement(result: MagneticFluxDensity): Boolean {
        val value = magnetometerBaseNoiseLevel ?: return false
        result.value = value
        result.unit = MagneticFluxDensityUnit.TESLA
        return true
    }

    /**
     * Norm of average magnetic flux density obtained during initialization and expressed in
     * Teslas (T).
     * This is only available once generator completes initialization.
     */
    var initialMagneticFluxDensityNorm: Double? = null
        private set

    /**
     * Gets norm of average magnetic flux density obtained during initialization.
     * This is only available once generator completes initialization.
     */
    val initialMagneticFluxDensityNormAsMeasurement: MagneticFluxDensity?
        get() {
            val value = initialMagneticFluxDensityNorm ?: return null
            return MagneticFluxDensity(value, MagneticFluxDensityUnit.TESLA)
        }

    /**
     * Gets norm of average magnetic flux density obtained during initialization.
     * This is only available once generator completes initialization.
     *
     * @param result instance where result will be stored.
     * @return true if result is available, false otherwise.
     */
    fun getInitialMagneticFluxDensityNormAsMeasurement(result: MagneticFluxDensity): Boolean {
        val value = initialMagneticFluxDensityNorm ?: return false
        result.value = value
        result.unit = MagneticFluxDensityUnit.TESLA
        return true
    }

    /**
     * Sample used by internal measurement generator.
     */
    override val sample = TimedBodyKinematicsAndMagneticFluxDensity()

    /**
     * Accelerometer sensor measurement expressed in NED coordinates.
     */
    private val nedMeasurement = AccelerometerSensorMeasurement()

    /**
     * Acceleration triad.
     */
    private val accelerationTriad = AccelerationTriad()

    /**
     * Body kinematics being reused for efficiency purposes.
     */
    private val kinematics = BodyKinematics()

    /**
     * Estimates accumulated average and noise of gyroscope values during static periods.
     */
    private val gyroscopeAccumulatedNoiseEstimator =
        AccumulatedAngularSpeedTriadNoiseEstimator()

    /**
     * Gyroscope sensor measurement expressed in NED coordinates.
     */
    private val nedGyroscopeMeasurement = GyroscopeSensorMeasurement()

    /**
     * Angular speed triad.
     */
    private val angularSpeedTriad = AngularSpeedTriad()

    /**
     * Body magnetic flux density being reused for efficiency purposes.
     */
    private val magneticFluxDensity = BodyMagneticFluxDensity()

    /**
     * Estimates accumulated average and noise of magnetometer values during static periods.
     */
    private val magnetometerAccumulatedNoiseEstimator =
        AccumulatedMagneticFluxDensityTriadNoiseEstimator()

    /**
     * Magnetometer sensor measurement expressed in NED coordinates.
     */
    private val nedMagnetometerMeasurement = MagnetometerSensorMeasurement()

    /**
     * Magnetic flux density triad.
     */
    private val magneticFluxDensityTriad = MagneticFluxDensityTriad()

    /**
     * Processes sample in internal measurements generator.
     */
    override fun processSampleInInternalGenerator() {
        measurementsGenerator.process(sample)
    }

    /**
     * Updates time interval of internal generator once the interval detector has been initialized.
     */
    override fun updateTimeIntervalOfInternalGenerator() {
        measurementsGenerator.timeInterval =
            accelerometerTimeIntervalEstimator.averageTimeInterval
    }

    /**
     * Processes an accelerometer measurement to generate an instance of type [BodyKinematics] to be
     * used by the internal measurement generator.
     * Since [AccelerometerMeasurementsGenerator] only requires acceleration information, no data is
     * provided for angular rates in processed result.
     *
     * @param measurement accelerometer sensor measurement.
     */
    override fun processAccelerometerData(
        measurement: AccelerometerSensorMeasurement,
        diffSeconds: Double,
        result: TimedBodyKinematicsAndMagneticFluxDensity
    ) {
        // convert from device ENU coordinates to local plane NED coordinates
        measurement.toNed(nedMeasurement)
        // convert to triad taking into account measurement bias if available
        nedMeasurement.toTriad(accelerationTriad)

        kinematics.specificForceTriad = accelerationTriad
        result.kinematics = kinematics
        result.magneticFluxDensity = magneticFluxDensity
        result.timestampSeconds = diffSeconds
    }

    /**
     * Processes a gyroscope measurement.
     *
     * @param measurement gyroscope sensor measurement.
     */
    fun processGyroscopeMeasurement(
        measurement: GyroscopeSensorMeasurement
    ) {
        // convert from device ENU coordinates to local plane NED coordinates
        measurement.toNed(nedGyroscopeMeasurement)
        nedGyroscopeMeasurement.toTriad(angularSpeedTriad)

        // set gyroscope information
        kinematics.angularRateTriad = angularSpeedTriad

        if (status == Status.INITIALIZING) {
            gyroscopeAccumulatedNoiseEstimator.addTriad(angularSpeedTriad)
        }

        numberOfProcessedGyroscopeMeasurements++

        if (gyroscopeBaseNoiseLevel == null && (status == Status.INITIALIZATION_COMPLETED
                    || status == Status.STATIC_INTERVAL || status == Status.DYNAMIC_INTERVAL)) {
            gyroscopeBaseNoiseLevel =
                gyroscopeAccumulatedNoiseEstimator.standardDeviationNorm
        }
    }

    /**
     * Processes a magnetometer measurement.
     *
     * @param measurement magnetometer sensor measurement.
     */
    fun processMagnetometerMeasurement(
        measurement: MagnetometerSensorMeasurement
    ) {
        measurement.toNed(nedMagnetometerMeasurement)
        nedMagnetometerMeasurement.toTriad(magneticFluxDensityTriad)

        magneticFluxDensity.setCoordinates(magneticFluxDensityTriad)

        if (status == Status.INITIALIZING) {
            magnetometerAccumulatedNoiseEstimator.addTriad(magneticFluxDensityTriad)
        }

        numberOfProcessedMagnetometerMeasurements++

        if (magnetometerBaseNoiseLevel == null && (status == Status.INITIALIZATION_COMPLETED
                    || status == Status.STATIC_INTERVAL || status == Status.DYNAMIC_INTERVAL)
        ) {
            magnetometerBaseNoiseLevel =
                magnetometerAccumulatedNoiseEstimator.standardDeviationNorm
            initialMagneticFluxDensityNorm = magnetometerAccumulatedNoiseEstimator.avgNorm
        }
    }

    /**
     * Resets generator to its initial state.
     */
    fun reset() {
        accelerometerTimeIntervalEstimator.totalSamples = Integer.MAX_VALUE
        accelerometerTimeIntervalEstimator.reset()
        measurementsGenerator.reset()
        unreliable = false
        initialAccelerometerTimestamp = 0L
        numberOfProcessedAccelerometerMeasurements = 0
        numberOfProcessedGyroscopeMeasurements = 0
        numberOfProcessedMagnetometerMeasurements = 0
        initialized = false
        gyroscopeBaseNoiseLevel = null
        gyroscopeAccumulatedNoiseEstimator.reset()
        magnetometerBaseNoiseLevel = null
        initialMagneticFluxDensityNorm = null
        magnetometerAccumulatedNoiseEstimator.reset()
    }

    /**
     * Interface to notify when processor's internal generator starts initialization.
     */
    fun interface OnInitializationStartedListener {

        /**
         * Called when initial static period starts so that base noise level starts being estimated.
         *
         * @param processor processor that raised the event.
         */
        fun onInitializationStarted(processor: AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor)
    }

    /**
     * Interface to notify when processor's internal generator completes its initialization.
     */
    fun interface OnInitializationCompletedListener {

        /**
         * Called when initial static period successfully completes and accelerometer base noise
         * level is estimated so that static and dynamic periods can be detected.
         *
         * @param processor processor that raised the event.
         * @param baseNoiseLevel base measurement noise level expressed in meters per squared second
         * (m/s^2).
         */
        fun onInitializationCompleted(
            processor: AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor,
            baseNoiseLevel: Double
        )
    }

    /**
     * Interface to notify when an error occurs.
     */
    fun interface OnErrorListener {

        /**
         * Called when an error is detected, either at initialization because excessive changes in
         * sensor measurements are found, or because sensor becomes unreliable.
         * When an error occurs, processors' internal generator is stopped and needs to be restarted
         * to be used again.
         *
         * @param processor processor that raised the event.
         * @param reason reason for error.
         */
        fun onError(
            processor: AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor,
            reason: ErrorReason
        )
    }

    /**
     * Interface to notify that a new static interval is detected.
     */
    fun interface OnStaticIntervalDetectedListener {

        /**
         * Called when a static interval has been detected after initialization.
         *
         * @param processor processor that raised the event.
         */
        fun onStaticIntervalDetected(
            processor: AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor
        )
    }

    /**
     * Interface to notify when a dynamic interval is detected.
     */
    fun interface OnDynamicIntervalDetectedListener {

        /**
         * Called when a dynamic interval has been detected after initialization.
         *
         * @param processor processor that raised the event.
         */
        fun onDynamicIntervalDetected(
            processor: AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor
        )
    }

    /**
     * Interface to notify when a static interval is skipped.
     * This happens when interval is too short.
     */
    fun interface OnStaticIntervalSkippedListener {

        /**
         * Called when a detected static interval is skipped because there are not enough samples to
         * be processed.
         *
         * @param processor processor that raised the event.
         */
        fun onStaticIntervalSkipped(
            processor: AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor
        )
    }

    /**
     * Interface to notify when a dynamic interval is skipped.
     * This happens when interval is too long.
     */
    fun interface OnDynamicIntervalSkippedListener {

        /**
         * Called when a detected dynamic interval is skipped because it has too many samples in it.
         *
         * @param processor processor that raised the event.
         */
        fun onDynamicIntervalSkipped(
            processor: AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor
        )
    }

    /**
     * Interface to notify when a new accelerometer calibration measurement is generated.
     */
    fun interface OnGeneratedAccelerometerMeasurementListener {

        /**
         * Called when a new calibration measurement is generated.
         *
         * @param processor processor that raised the event.
         * @param measurement generated accelerometer calibration measurement.
         */
        fun onGeneratedAccelerometerMeasurement(
            processor: AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor,
            measurement: StandardDeviationBodyKinematics
        )
    }

    /**
     * Interface to notify when a new gyroscope calibration measurement is generated.
     */
    fun interface OnGeneratedGyroscopeMeasurementListener {

        /**
         * Called when a new gyroscope calibration measurement is generated.
         *
         * @param processor processor that raised the event.
         * @param measurement generated gyroscope calibration measurement.
         */
        fun onGeneratedGyroscopeMeasurement(
            processor: AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor,
            measurement: BodyKinematicsSequence<StandardDeviationTimedBodyKinematics>
        )
    }

    /**
     * Interface to notify when a new magnetometer calibration measurement is generated.
     */
    fun interface OnGeneratedMagnetometerMeasurementListener {

        /**
         * Called when a new magnetometer calibration measurement is generated.
         *
         * @param processor processor that raised the event.
         * @param measurement generated magnetometer calibration measurement.
         */
        fun onGeneratedMagnetometerMeasurement(
            processor: AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor,
            measurement: StandardDeviationBodyMagneticFluxDensity
        )
    }

    /**
     * Interface to notify when generator is reset (occurs when starting after stopping the
     * generator)
     */
    fun interface OnResetListener {
        /**
         * Called when processor is reset.
         *
         * @param processor processor that raised the event.
         */
        fun onReset(processor: AccelerometerGyroscopeAndMagnetometerMeasurementGeneratorProcessor)
    }
}