/*
 * Copyright (C) 2025 Alberto Irurueta Carro (alberto@irurueta.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.irurueta.android.navigation.inertial.calibration.intervals.measurements

import android.content.Context
import com.irurueta.android.navigation.inertial.calibration.intervals.ErrorReason
import com.irurueta.android.navigation.inertial.collectors.GyroscopeSensorCollector
import com.irurueta.android.navigation.inertial.collectors.SensorCollector
import com.irurueta.android.navigation.inertial.collectors.SensorDelay
import com.irurueta.android.navigation.inertial.collectors.measurements.AccelerometerSensorType
import com.irurueta.android.navigation.inertial.collectors.measurements.GyroscopeSensorMeasurement
import com.irurueta.android.navigation.inertial.collectors.measurements.GyroscopeSensorType
import com.irurueta.navigation.inertial.calibration.BodyKinematicsSequence
import com.irurueta.navigation.inertial.calibration.StandardDeviationBodyKinematics
import com.irurueta.navigation.inertial.calibration.StandardDeviationTimedBodyKinematics
import com.irurueta.navigation.inertial.calibration.TimedBodyKinematics
import com.irurueta.units.AngularSpeed

/**
 * Generates measurements that can later be used both by accelerometer and gyroscope calibrators.
 * Measurements are generated by taking into account static and dynamic intervals on the device,
 * when the device is kept static (e.g. motionless), or when some force is applied to the device
 * changing its position or orientation.
 * Static and dynamic intervals are always measured using the accelerometer.
 * Additionally, the gyroscope is also used, and measurements are generated to calibrate both
 * accelerometers and gyroscopes.
 * Measurement generator converts device ENU measurements into measurements expressed in local
 * tangent plane NED coordinates.
 *
 * @property context Android context.
 * @property accelerometerSensorType One of the supported accelerometer sensor types.
 * @property accelerometerSensorDelay Delay of accelerometer sensor between samples.
 * @property gyroscopeSensorType One of the supported gyroscope sensor types.
 * @property gyroscopeSensorDelay Delay of gyroscope sensor between samples.
 * @property initializationStartedListener listener to notify when initialization starts.
 * @property initializationCompletedListener listener to notify when initialization successfully
 * completes.
 * @property errorListener listener to notify errors.
 * @property staticIntervalDetectedListener listener to notify when a static interval is detected.
 * @property dynamicIntervalDetectedListener listener to notify when a dynamic interval is detected.
 * @property staticIntervalSkippedListener listener to notify when a static interval is skipped if
 * its duration is too short.
 * @property dynamicIntervalSkippedListener listener to notify when a dynamic interval is skipped if
 * its duration is too long.
 * @property generatedAccelerometerMeasurementListener listener to notify when a new accelerometer
 * calibration measurement is generated.
 * @property generatedGyroscopeMeasurementListener listener to notify when a new gyroscope
 * calibration measurement is generated.
 * @property resetListener listener to notify when generator is restarted.
 */
class AccelerometerAndGyroscopeMeasurementGenerator(
    context: Context,
    accelerometerSensorType: AccelerometerSensorType =
        AccelerometerSensorType.ACCELEROMETER_UNCALIBRATED,
    accelerometerSensorDelay: SensorDelay = SensorDelay.FASTEST,
    val gyroscopeSensorType: GyroscopeSensorType = GyroscopeSensorType.GYROSCOPE_UNCALIBRATED,
    val gyroscopeSensorDelay: SensorDelay = SensorDelay.FASTEST,
    var initializationStartedListener: OnInitializationStartedListener? = null,
    var initializationCompletedListener: OnInitializationCompletedListener? = null,
    var errorListener: OnErrorListener? = null,
    var staticIntervalDetectedListener: OnStaticIntervalDetectedListener? = null,
    var dynamicIntervalDetectedListener: OnDynamicIntervalDetectedListener? = null,
    var staticIntervalSkippedListener: OnStaticIntervalSkippedListener? = null,
    var dynamicIntervalSkippedListener: OnDynamicIntervalSkippedListener? = null,
    var generatedAccelerometerMeasurementListener: OnGeneratedAccelerometerMeasurementListener? = null,
    var generatedGyroscopeMeasurementListener: OnGeneratedGyroscopeMeasurementListener? = null,
    var resetListener: OnResetListener? = null
) : CalibrationMeasurementGenerator<TimedBodyKinematics,
        AccelerometerAndGyroscopeMeasurementGeneratorProcessor>(
    context,
    accelerometerSensorType,
    accelerometerSensorDelay
) {
    /**
     * Internal processor to process accelerometer and gyroscope sensor measurements.
     */
    override val processor = AccelerometerAndGyroscopeMeasurementGeneratorProcessor(
        initializationStartedListener = { _ ->
            initializationStartedListener?.onInitializationStarted(
                this
            )
        },
        initializationCompletedListener = { _, baseNoiseLevel ->
            initializationCompletedListener?.onInitializationCompleted(
                this,
                baseNoiseLevel
            )
        },
        errorListener = { _, reason -> errorListener?.onError(this, reason) },
        staticIntervalDetectedListener = { _ ->
            staticIntervalDetectedListener?.onStaticIntervalDetected(
                this
            )
        },
        dynamicIntervalDetectedListener = { _ ->
            dynamicIntervalDetectedListener?.onDynamicIntervalDetected(
                this
            )
        },
        staticIntervalSkippedListener = { _ ->
            staticIntervalSkippedListener?.onStaticIntervalSkipped(
                this
            )
        },
        dynamicIntervalSkippedListener = { _ ->
            dynamicIntervalSkippedListener?.onDynamicIntervalSkipped(
                this
            )
        },
        generatedAccelerometerMeasurementListener = { _, measurement ->
            generatedAccelerometerMeasurementListener?.onGeneratedAccelerometerMeasurement(
                this,
                measurement
            )
        },
        generatedGyroscopeMeasurementListener = { _, measurement ->
            generatedGyroscopeMeasurementListener?.onGeneratedGyroscopeMeasurement(
                this,
                measurement
            )
        },
        resetListener = { _ -> resetListener?.onReset(this) }
    )

    /**
     * Internal listener for gyroscope sensor collector.
     * Handles measurements collected by the gyroscope sensor so that they are processed by
     * the internal measurement generator.
     */
    private val gyroscopeCollectorMeasurementListener =
        SensorCollector.OnMeasurementListener<GyroscopeSensorMeasurement, GyroscopeSensorCollector> { _, measurement ->
            processor.processGyroscopeMeasurement(measurement)
        }

    /**
     * Listener to detect when accuracy of gyroscope sensor changes.
     * When sensor becomes unreliable, an error is notified.
     */
    private val gyroscopeAccuracyChangedListener =
        SensorCollector.OnAccuracyChangedListener<GyroscopeSensorMeasurement, GyroscopeSensorCollector> { _, accuracy ->
            processAccuracyChange(accuracy)
        }

    /**
     * Gyroscope sensor collector.
     * Collects gyroscope measurements.
     */
    private val gyroscopeCollector = GyroscopeSensorCollector(
        context,
        gyroscopeSensorType,
        gyroscopeSensorDelay,
        gyroscopeAccuracyChangedListener,
        gyroscopeCollectorMeasurementListener
    )

    /**
     * Starts collection of sensor measurements.
     *
     * @throws IllegalStateException if generator is already running or sensor is not available.
     */
    @Throws(IllegalStateException::class)
    override fun start() {
        check(!running)
        reset()

        running = true
        if (!accelerometerCollector.start()) {
            running = false
            throw IllegalStateException("Unavailable accelerometer sensor")
        }
        if (!gyroscopeCollector.start()) {
            stop()
            throw IllegalStateException("Unavailable gyroscope sensor")
        }
    }

    /**
     * Stops collection of sensor measurements.
     */
    override fun stop() {
        gyroscopeCollector.stop()
        accelerometerCollector.stop()
        running = false
    }

    /**
     * Gets gyroscope sensor being used to obtain measurements, or null if not available.
     * This can be used to obtain additional information about the sensor.
     */
    val gyroscopeSensor
        get() = gyroscopeCollector.sensor

    /**
     * Number of gyroscope measurements that have been processed.
     */
    val numberOfProcessedGyroscopeMeasurements: Int
        get() = processor.numberOfProcessedGyroscopeMeasurements

    /**
     * Gets gyroscope measurement base noise level that has been detected during initialization
     * expressed in radians per second (rad/s).
     * This is only available once generator completes initialization.
     */
    val gyroscopeBaseNoiseLevel: Double?
        get() = processor.gyroscopeBaseNoiseLevel

    /**
     * Gets gyroscope measurement base noise level that has been detected during initialization.
     * This is only available once generator completes initialization.
     */
    val gyroscopeBaseNoiseLevelAsMeasurement: AngularSpeed?
        get() = processor.gyroscopeBaseNoiseLevelAsMeasurement

    /**
     * Gets gyroscope measurement base noise level that has been detected during initialization.
     * This is only available once generator completes initialization.
     *
     * @param result instance where result will be stored.
     * @return true if result is available, false otherwise.
     */
    fun getGyroscopeBaseNoiseLevelAsMeasurement(result: AngularSpeed): Boolean {
        return processor.getGyroscopeBaseNoiseLevelAsMeasurement(result)
    }

    /**
     * Notifies that sensor has become unreliable.
     */
    override fun notifyUnreliableSensor() {
        errorListener?.onError(
            this@AccelerometerAndGyroscopeMeasurementGenerator,
            ErrorReason.UNRELIABLE_SENSOR
        )
    }

    /**
     * Resets generator to its initial state.
     */
    private fun reset() {
        processor.reset()
    }

    /**
     * Interface to notify when processor's internal generator starts initialization.
     */
    fun interface OnInitializationStartedListener {

        /**
         * Called when initial static period starts so that base noise level starts being estimated.
         *
         * @param generator generator that raised the event.
         */
        fun onInitializationStarted(generator: AccelerometerAndGyroscopeMeasurementGenerator)
    }

    /**
     * Interface to notify when processor's internal generator completes its initialization.
     */
    fun interface OnInitializationCompletedListener {

        /**
         * Called when initial static period successfully completes and accelerometer base noise
         * level is estimated so that static and dynamic periods can be detected.
         *
         * @param generator generator that raised the event.
         * @param baseNoiseLevel base measurement noise level expressed in meters per squared second
         * (m/s^2).
         */
        fun onInitializationCompleted(
            generator: AccelerometerAndGyroscopeMeasurementGenerator,
            baseNoiseLevel: Double
        )
    }

    /**
     * Interface to notify when an error occurs.
     */
    fun interface OnErrorListener {

        /**
         * Called when an error is detected, either at initialization because excessive changes in
         * sensor measurements are found, or because sensor becomes unreliable.
         * When an error occurs, processors' internal generator is stopped and needs to be restarted
         * to be used again.
         *
         * @param generator generator that raised the event.
         * @param reason reason for error.
         */
        fun onError(
            generator: AccelerometerAndGyroscopeMeasurementGenerator,
            reason: ErrorReason
        )
    }

    /**
     * Interface to notify that a new static interval is detected.
     */
    fun interface OnStaticIntervalDetectedListener {

        /**
         * Called when a static interval has been detected after initialization.
         *
         * @param generator generator that raised the event.
         */
        fun onStaticIntervalDetected(
            generator: AccelerometerAndGyroscopeMeasurementGenerator
        )
    }

    /**
     * Interface to notify when a dynamic interval is detected.
     */
    fun interface OnDynamicIntervalDetectedListener {

        /**
         * Called when a dynamic interval has been detected after initialization.
         *
         * @param generator generator that raised the event.
         */
        fun onDynamicIntervalDetected(
            generator: AccelerometerAndGyroscopeMeasurementGenerator
        )
    }

    /**
     * Interface to notify when a static interval is skipped.
     * This happens when interval is too short.
     */
    fun interface OnStaticIntervalSkippedListener {

        /**
         * Called when a detected static interval is skipped because there are not enough samples to
         * be processed.
         *
         * @param generator generator that raised the event.
         */
        fun onStaticIntervalSkipped(
            generator: AccelerometerAndGyroscopeMeasurementGenerator
        )
    }

    /**
     * Interface to notify when a dynamic interval is skipped.
     * This happens when interval is too long.
     */
    fun interface OnDynamicIntervalSkippedListener {

        /**
         * Called when a detected dynamic interval is skipped because it has too many samples in it.
         *
         * @param generator generator that raised the event.
         */
        fun onDynamicIntervalSkipped(
            generator: AccelerometerAndGyroscopeMeasurementGenerator
        )
    }

    /**
     * Interface to notify when a new accelerometer calibration measurement is generated.
     */
    fun interface OnGeneratedAccelerometerMeasurementListener {

        /**
         * Called when a new calibration measurement is generated.
         *
         * @param generator generator that raised the event.
         * @param measurement generated accelerometer calibration measurement.
         */
        fun onGeneratedAccelerometerMeasurement(
            generator: AccelerometerAndGyroscopeMeasurementGenerator,
            measurement: StandardDeviationBodyKinematics
        )
    }

    /**
     * Interface to notify when a new gyroscope calibration measurement is generated.
     */
    fun interface OnGeneratedGyroscopeMeasurementListener {

        /**
         * Called when a new gyroscope calibration measurement is generated.
         *
         * @param generator generator that raised the event.
         * @param measurement generated gyroscope calibration measurement.
         */
        fun onGeneratedGyroscopeMeasurement(
            generator: AccelerometerAndGyroscopeMeasurementGenerator,
            measurement: BodyKinematicsSequence<StandardDeviationTimedBodyKinematics>
        )
    }

    /**
     * Interface to notify when generator is reset (occurs when starting after stopping the
     * generator)
     */
    fun interface OnResetListener {
        /**
         * Called when processor is reset.
         *
         * @param generator processor that raised the event.
         */
        fun onReset(generator: AccelerometerAndGyroscopeMeasurementGenerator)
    }
}