/*
 * Copyright (C) 2025 Alberto Irurueta Carro (alberto@irurueta.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.irurueta.android.navigation.inertial.calibration.intervals.measurements

import android.content.Context
import com.irurueta.android.navigation.inertial.calibration.intervals.Status
import com.irurueta.android.navigation.inertial.collectors.AccelerometerSensorCollector
import com.irurueta.android.navigation.inertial.collectors.SensorCollector
import com.irurueta.android.navigation.inertial.collectors.SensorDelay
import com.irurueta.android.navigation.inertial.collectors.measurements.AccelerometerSensorMeasurement
import com.irurueta.android.navigation.inertial.collectors.measurements.AccelerometerSensorType
import com.irurueta.android.navigation.inertial.collectors.measurements.SensorAccuracy
import com.irurueta.navigation.inertial.calibration.intervals.TriadStaticIntervalDetector
import com.irurueta.units.Acceleration
import com.irurueta.units.Time

/**
 * Base class to generate calibration measurements.
 * Measurements are generated by taking into account static and dynamic intervals on the device,
 * where the device is kept static (e.g. motionless), or where some force is applied to the device
 * changing its position or orientation.
 * Static and dynamic intervals are always measured using the accelerometer. An additional sensor
 * such as the gyroscope or magnetometer can be used to generate measurements for them.
 * Measurement generator converts device ENU measurements into measurements expressed in local
 * tangent plane NED coordinates.
 *
 * @property context Android context.
 * @property accelerometerSensorType One of the supported accelerometer sensor types.
 * @property accelerometerSensorDelay Delay of sensor between samples.
 * @param I type of input data to be processed.
 * @param P type of internal processor.
 */
abstract class CalibrationMeasurementGenerator<I, P : CalibrationMeasurementGeneratorProcessor<I>>(
    val context: Context,
    val accelerometerSensorType: AccelerometerSensorType =
        AccelerometerSensorType.ACCELEROMETER_UNCALIBRATED,
    val accelerometerSensorDelay: SensorDelay = SensorDelay.FASTEST
) {
    /**
     * Internal processor to process sensor measurements.
     */
    protected abstract val processor: P

    /**
     * Gets or sets minimum number of samples required in a static interval to be taken into
     * account. Smaller static intervals will be discarded.
     *
     * @throws IllegalArgumentException if provided value is less than 2.
     * @throws IllegalStateException if generator is currently running.
     */
    var minStaticSamples: Int
        get() = processor.minStaticSamples
        @Throws(IllegalArgumentException::class, IllegalStateException::class)
        set(value) {
            check(!running)
            processor.minStaticSamples = value
        }

    /**
     * Gets or sets maximum number of samples allowed in dynamic intervals.
     * Dynamic intervals exceeding this value are discarded.
     *
     * @throws IllegalArgumentException if provided value is less than 2.
     * @throws IllegalStateException if generator is currently running.
     */
    var maxDynamicSamples: Int
        get() = processor.maxDynamicSamples
        @Throws(IllegalArgumentException::class, IllegalStateException::class)
        set(value) {
            check(!running)
            processor.maxDynamicSamples = value
        }

    /**
     * Gets or sets length of number of samples to keep within the window being processed to
     * determine instantaneous sensor noise level. Window size must always be larger than
     * allowed minimum value, which is 2 and must have an odd value.
     *
     * @throws IllegalArgumentException if provided value is not valid.
     * @throws IllegalStateException if generator is currently running.
     */
    var windowSize: Int
        get() = processor.windowSize
        @Throws(IllegalArgumentException::class, IllegalStateException::class)
        set(value) {
            check(!running)
            processor.windowSize = value
        }

    /**
     * Gets or sets number of samples to be processed initially while keeping the sensor static in
     * order to find the base noise level when device is static.
     *
     * @throws IllegalArgumentException if provided value is less than
     * [TriadStaticIntervalDetector.MINIMUM_INITIAL_STATIC_SAMPLES].
     * @throws IllegalStateException if generator is currently running.
     */
    var initialStaticSamples: Int
        get() = processor.initialStaticSamples
        @Throws(IllegalArgumentException::class, IllegalStateException::class)
        set(value) {
            check(!running)
            processor.initialStaticSamples = value
        }

    /**
     * Gets or sets factor to be applied to detected base noise level in order to determine
     * threshold for static/dynamic period changes. This factor is unit-less.
     *
     * @throws IllegalArgumentException if provided value is zero or negative
     * @throws IllegalStateException if generator is currently running.
     */
    var thresholdFactor: Double
        get() = processor.thresholdFactor
        @Throws(IllegalArgumentException::class, IllegalStateException::class)
        set(value) {
            check(!running)
            processor.thresholdFactor = value
        }

    /**
     * Gets or sets factor to determine that a sudden movement has occurred during initialization if
     * instantaneous noise level exceeds accumulated noise level by this factor amount. This factor
     * is unit-less.
     *
     * @throws IllegalArgumentException if provided value is zero or negative.
     * @throws IllegalStateException if generator is currently running
     */
    var instantaneousNoiseLevelFactor: Double
        get() = processor.instantaneousNoiseLevelFactor
        @Throws(IllegalArgumentException::class, IllegalStateException::class)
        set(value) {
            check(!running)
            processor.instantaneousNoiseLevelFactor = value
        }

    /**
     * Gets or sets overall absolute threshold to determine whether there has been excessive motion
     * during the whole initialization phase. Failure will be detected if estimated base noise level
     * exceeds this threshold when initialization completes. This threshold is expressed in meters
     * per squared second (m/s^2).
     *
     * @throws IllegalArgumentException if provided value is zero or negative.
     * @throws IllegalStateException if detector is currently running.
     */
    var baseNoiseLevelAbsoluteThreshold: Double
        get() = processor.baseNoiseLevelAbsoluteThreshold
        @Throws(IllegalArgumentException::class, IllegalStateException::class)
        set(value) {
            check(!running)
            processor.baseNoiseLevelAbsoluteThreshold = value
        }

    /**
     * Gets or sets overall absolute threshold to determine whether there has been excessive motion
     * during the whole initialization phase. Failure will be detected if estimated base noise level
     * exceeds this threshold when initialization completes.
     *
     * @throws IllegalArgumentException if provided value is zero or negative.
     * @throws IllegalStateException if detector is currently running.
     */
    var baseNoiseLevelAbsoluteThresholdAsMeasurement: Acceleration
        get() = processor.baseNoiseLevelAbsoluteThresholdAsMeasurement
        @Throws(IllegalArgumentException::class, IllegalStateException::class)
        set(value) {
            check(!running)
            processor.baseNoiseLevelAbsoluteThresholdAsMeasurement = value
        }

    /**
     * Gets overall absolute threshold to determine whether there has been excessive motion during
     * the whole initialization phase. Failure will be detected if estimated base noise level
     * exceeds this threshold when initialization completes.
     *
     * @param result instance where result will be stored.
     */
    fun getBaseNoiseLevelAbsoluteThresholdAsMeasurement(result: Acceleration) {
        processor.getBaseNoiseLevelAbsoluteThresholdAsMeasurement(result)
    }

    /**
     * Gets accelerometer measurement base noise level that has been detected during initialization
     * expressed in meters per squared second (m/s^2).
     * This is only available once detector completes initialization.
     */
    val accelerometerBaseNoiseLevel: Double?
        get() = processor.accelerometerBaseNoiseLevel

    /**
     * Gets sensor measurement base noise level that has been detected during initialization.
     * This is only available once detector completes initialization.
     */
    val accelerometerBaseNoiseLevelAsMeasurement: Acceleration?
        get() = processor.accelerometerBaseNoiseLevelAsMeasurement

    /**
     * Gets sensor measurement base noise level that has been detected during initialization.
     * This is only available once detector completes initialization.
     *
     * @param result instance where result will be stored.
     * @return true if result is available, false otherwise.
     */
    fun getAccelerometerBaseNoiseLevelAsMeasurement(result: Acceleration): Boolean {
        return processor.getAccelerometerBaseNoiseLevelAsMeasurement(result)
    }

    /**
     * Gets measurement base noise level PSD (Power Spectral Density) expressed in (m^2 * s^-3).
     * This is only available once detector completes initialization.
     */
    val accelerometerBaseNoiseLevelPsd: Double?
        get() = processor.accelerometerBaseNoiseLevelPsd

    /**
     * Gets measurement base noise level root PSD (Power Spectral Density) expressed
     * in (m * s^-1.5).
     * This is only available once detector completes initialization.
     */
    val accelerometerBaseNoiseLevelRootPsd: Double?
        get() = processor.accelerometerBaseNoiseLevelRootPsd

    /**
     * Gets estimated threshold to determine static/dynamic period changes expressed in meters per
     * squared second (m/s^2).
     * This is only available once detector completes initialization.
     */
    val threshold: Double?
        get() = processor.threshold

    /**
     * Gets estimated threshold to determine static/dynamic period changes.
     * This is only available once detector completes initialization.
     */
    val thresholdAsMeasurement: Acceleration?
        get() = processor.thresholdAsMeasurement

    /**
     * Gets estimated threshold to determine static/dynamic period changes.
     * This is only available once detector completes initialization.
     *
     * @param result instance where result will be stored.
     * @return true if result is available, false otherwise.
     */
    fun getThresholdAsMeasurement(result: Acceleration): Boolean {
        return processor.getThresholdAsMeasurement(result)
    }

    /**
     * Gets number of samples that have been processed in a static period so far.
     */
    val processedStaticSamples: Int
        get() = processor.processedStaticSamples

    /**
     * Gets number of samples that have been processed in a dynamic period so far.
     */
    val processedDynamicSamples: Int
        get() = processor.processedDynamicSamples

    /**
     * Indicates whether last static interval must be skipped.
     */
    val isStaticIntervalSkipped: Boolean
        get() = processor.isStaticIntervalSkipped

    /**
     * Indicates whether last dynamic interval must be skipped.
     */
    val isDynamicIntervalSkipped: Boolean
        get() = processor.isDynamicIntervalSkipped

    /**
     * Gets average time interval between accelerometer samples expressed in seconds (s).
     * This is only available once this generator completes initialization.
     */
    val accelerometerAverageTimeInterval: Double?
        get() = processor.accelerometerAverageTimeInterval

    /**
     * Gets average time interval between accelerometer samples.
     * This is only available once this generator completes initialization.
     */
    val accelerometerAverageTimeIntervalAsTime: Time?
        get() = processor.accelerometerAverageTimeIntervalAsTime

    /**
     * Gets average time interval between accelerometer measurements.
     * This is only available once detector completes initialization.
     *
     * @param result instance where result will be stored.
     * @return true if result is available, false otherwise.
     */
    fun getAccelerometerAverageTimeIntervalAsTime(result: Time): Boolean {
        return processor.getAccelerometerAverageTimeIntervalAsTime(result)
    }

    /**
     * Gets estimated variance of time interval between accelerometer measurements expressed in
     * squared seconds (s^2).
     * This is only available once detector completes initialization.
     */
    val accelerometerTimeIntervalVariance: Double?
        get() = processor.accelerometerTimeIntervalVariance

    /**
     * Gets estimated standard deviation of time interval between accelerometer measurements
     * expressed in seconds (s).
     * This is only available once detector completes initialization.
     */
    val accelerometerTimeIntervalStandardDeviation: Double?
        get() = processor.accelerometerTimeIntervalStandardDeviation

    /**
     * Gets estimated standard deviation of time interval between accelerometer measurements.
     * This is only available once detector completes initialization.
     */
    val accelerometerTimeIntervalStandardDeviationAsTime: Time?
        get() = processor.accelerometerTimeIntervalStandardDeviationAsTime

    /**
     * Gets estimated standard deviation of time interval between accelerometer measurements.
     * This is only available once detector completes initialization.
     *
     * @param result instance where result will be stored.
     * @return true if result is available, false otherwise.
     */
    fun getAccelerometerTimeIntervalStandardDeviationAsTime(result: Time): Boolean {
        return processor.getAccelerometerTimeIntervalStandardDeviationAsTime(result)
    }

    /**
     * Number of accelerometer measurements that have been processed.
     */
    val numberOfProcessedAccelerometerMeasurements: Int
        get() = processor.numberOfProcessedAccelerometerMeasurements

    /**
     * Indicates whether this generator is already running.
     */
    var running = false
        protected set

    /**
     * Gets status of measurement generator.
     * Initially the generator will be idle.
     * Once it starts, it will start the initialization phase, and once
     * initialization is complete, it will switch between static or dynamic interval
     * until generator is stopped or an error occurs.
     */
    val status: Status
        get() = processor.status

    /**
     * Starts collection of sensor measurements.
     *
     * @throws IllegalStateException if generator is already running or sensor is not available.
     */
    @Throws(IllegalStateException::class)
    abstract fun start()

    /**
     * Stops collection of sensor measurements.
     */
    abstract fun stop()

    /**
     * Processes sensor accuracy changes.
     *
     * @param accuracy New sensor accuracy.
     */
    protected fun processAccuracyChange(accuracy: SensorAccuracy?) {
        if (accuracy == SensorAccuracy.UNRELIABLE) {
            stop()
            processor.unreliable = true
            notifyUnreliableSensor()
        }
    }

    /**
     * Notifies that sensor has become unreliable.
     */
    protected abstract fun notifyUnreliableSensor()

    /**
     * Internal listener for accelerometer sensor collector.
     * Handles measurements collected by the accelerometer sensor so that they are processed by
     * the internal measurement generator.
     */
    private val accelerometerCollectorMeasurementListener =
        SensorCollector.OnMeasurementListener<AccelerometerSensorMeasurement, AccelerometerSensorCollector> { _, measurement ->
            processor.processAccelerometerMeasurement(measurement)
        }

    /**
     * Listener to detect when accuracy of accelerometer sensor changes.
     * When sensor becomes unreliable, an error is notified.
     */
    private val accelerometerAccuracyChangedListener =
        SensorCollector.OnAccuracyChangedListener<AccelerometerSensorMeasurement, AccelerometerSensorCollector> { _, accuracy ->
            processAccuracyChange(accuracy)
        }

    /**
     * Accelerometer sensor collector.
     * Collects accelerometer measurements.
     */
    protected val accelerometerCollector = AccelerometerSensorCollector(
        context,
        accelerometerSensorType,
        accelerometerSensorDelay,
        accelerometerAccuracyChangedListener,
        accelerometerCollectorMeasurementListener
    )

    /**
     * Gets accelerometer sensor being used to obtain measurements and detect static/dynamic
     * intervals, or null if not available.
     * This can be used to obtain additional information about the sensor.
     */
    val accelerometerSensor
        get() = accelerometerCollector.sensor
}