/*
 * Copyright (C) 2025 Alberto Irurueta Carro (alberto@irurueta.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.irurueta.android.navigation.inertial.calibration.intervals.measurements

import com.irurueta.android.navigation.inertial.calibration.intervals.Status
import com.irurueta.android.navigation.inertial.collectors.measurements.AccelerometerSensorMeasurement
import com.irurueta.android.navigation.inertial.collectors.measurements.GyroscopeSensorMeasurement
import com.irurueta.navigation.inertial.BodyKinematics
import com.irurueta.navigation.inertial.calibration.AccelerationTriad
import com.irurueta.navigation.inertial.calibration.AngularSpeedTriad
import com.irurueta.navigation.inertial.calibration.BodyKinematicsSequence
import com.irurueta.navigation.inertial.calibration.StandardDeviationTimedBodyKinematics
import com.irurueta.navigation.inertial.calibration.TimedBodyKinematics
import com.irurueta.navigation.inertial.calibration.generators.GyroscopeMeasurementsGenerator
import com.irurueta.navigation.inertial.calibration.generators.GyroscopeMeasurementsGeneratorListener
import com.irurueta.navigation.inertial.calibration.intervals.TriadStaticIntervalDetector
import com.irurueta.navigation.inertial.calibration.noise.AccumulatedAngularSpeedTriadNoiseEstimator
import com.irurueta.units.AngularSpeed
import com.irurueta.units.AngularSpeedUnit

/**
 * Generates measurements that can later be used by gyroscope calibrators.
 * Measurements are generated by taking into account static and dynamic intervals on the device,
 * when the device is kept static (e.g. motionless), or when some force is applied to the device
 * changing its position or orientation.
 * Measurement generator converts device ENU measurements into measurements expressed in local
 * tangent plane NED coordinates.
 *
 * @param initializationStartedListener listener to notify when initialization starts.
 * @property initializationCompletedListener listener to notify when initialization successfully
 * completes.
 * @property errorListener listener to notify errors.
 * @property staticIntervalDetectedListener listener to notify when a static interval is detected.
 * @property dynamicIntervalDetectedListener listener to notify when a dynamic interval is detected.
 * @property staticIntervalSkippedListener listener to notify when a static interval is skipped if
 * its duration is too short.
 * @property dynamicIntervalSkippedListener listener to notify when a dynamic interval is skipped if
 * its duration is too long.
 * @property generatedMeasurementListener listener to notify when a new calibration measurement is
 * generated.
 * @property resetListener listener to notify when generator is restarted.
 */
class GyroscopeMeasurementGeneratorProcessor(
    initializationStartedListener: OnInitializationStartedListener<GyroscopeMeasurementGeneratorProcessor>? = null,
    initializationCompletedListener: OnInitializationCompletedListener<GyroscopeMeasurementGeneratorProcessor>? = null,
    errorListener: OnErrorListener<GyroscopeMeasurementGeneratorProcessor>? = null,
    staticIntervalDetectedListener: OnStaticIntervalDetectedListener<GyroscopeMeasurementGeneratorProcessor>? = null,
    dynamicIntervalDetectedListener: OnDynamicIntervalDetectedListener<GyroscopeMeasurementGeneratorProcessor>? = null,
    staticIntervalSkippedListener: OnStaticIntervalSkippedListener<GyroscopeMeasurementGeneratorProcessor>? = null,
    dynamicIntervalSkippedListener: OnDynamicIntervalSkippedListener<GyroscopeMeasurementGeneratorProcessor>? = null,
    generatedMeasurementListener: OnGeneratedMeasurementListener<GyroscopeMeasurementGeneratorProcessor, BodyKinematicsSequence<StandardDeviationTimedBodyKinematics>>? = null,
    resetListener: OnResetListener<GyroscopeMeasurementGeneratorProcessor>? = null
) : SingleSensorCalibrationMeasurementGeneratorProcessor<GyroscopeMeasurementGeneratorProcessor,
        BodyKinematicsSequence<StandardDeviationTimedBodyKinematics>,
        GyroscopeMeasurementsGenerator,
        GyroscopeMeasurementsGeneratorListener,
        TimedBodyKinematics>(
    initializationStartedListener,
    initializationCompletedListener,
    errorListener,
    staticIntervalDetectedListener,
    dynamicIntervalDetectedListener,
    staticIntervalSkippedListener,
    dynamicIntervalSkippedListener,
    generatedMeasurementListener,
    resetListener
) {
    /**
     * Number of gyroscope measurements that have been processed.
     */
    var numberOfProcessedGyroscopeMeasurements: Int = 0
        private set

    /**
     * Gets gyroscope measurement base noise level that has been detected during initialization
     * expressed in radians per second (rad/s).
     * This is only available once generator completes initialization.
     */
    var gyroscopeBaseNoiseLevel: Double? = null
        private set

    /**
     * Gets gyroscope measurement base noise level that has been detected during initialization.
     * This is only available once generator completes initialization.
     */
    val gyroscopeBaseNoiseLevelAsMeasurement: AngularSpeed?
        get() {
            val value = gyroscopeBaseNoiseLevel ?: return null
            return AngularSpeed(value, AngularSpeedUnit.RADIANS_PER_SECOND)
        }

    /**
     * Gets gyroscope measurement base noise level that has been detected during initialization.
     * This is only available once generator completes initialization.
     *
     * @param result instance where result will be stored.
     * @return true if result is available, false otherwise.
     */
    fun getGyroscopeBaseNoiseLevelAsMeasurement(result: AngularSpeed): Boolean {
        val value = gyroscopeBaseNoiseLevel ?: return false
        result.value = value
        result.unit = AngularSpeedUnit.RADIANS_PER_SECOND
        return true
    }

    /**
     * Listener for internal measurement generator.
     */
    override val measurementsGeneratorListener = object : GyroscopeMeasurementsGeneratorListener {
        override fun onInitializationStarted(generator: GyroscopeMeasurementsGenerator?) {
            initializationStartedListener?.onInitializationStarted(
                this@GyroscopeMeasurementGeneratorProcessor
            )
        }

        override fun onInitializationCompleted(
            generator: GyroscopeMeasurementsGenerator?,
            baseNoiseLevel: Double
        ) {
            initializationCompletedListener?.onInitializationCompleted(
                this@GyroscopeMeasurementGeneratorProcessor,
                baseNoiseLevel
            )
        }

        override fun onError(
            generator: GyroscopeMeasurementsGenerator?,
            reason: TriadStaticIntervalDetector.ErrorReason
        ) {
            errorListener?.onError(this@GyroscopeMeasurementGeneratorProcessor,
                mapErrorReason(reason))
        }

        override fun onStaticIntervalDetected(generator: GyroscopeMeasurementsGenerator?) {
            staticIntervalDetectedListener?.onStaticIntervalDetected(
                this@GyroscopeMeasurementGeneratorProcessor
            )
        }

        override fun onDynamicIntervalDetected(generator: GyroscopeMeasurementsGenerator?) {
            dynamicIntervalDetectedListener?.onDynamicIntervalDetected(
                this@GyroscopeMeasurementGeneratorProcessor
            )
        }

        override fun onStaticIntervalSkipped(generator: GyroscopeMeasurementsGenerator?) {
            staticIntervalSkippedListener?.onStaticIntervalSkipped(
                this@GyroscopeMeasurementGeneratorProcessor
            )
        }

        override fun onDynamicIntervalSkipped(generator: GyroscopeMeasurementsGenerator?) {
            dynamicIntervalSkippedListener?.onDynamicIntervalSkipped(
                this@GyroscopeMeasurementGeneratorProcessor
            )
        }

        override fun onGeneratedMeasurement(
            generator: GyroscopeMeasurementsGenerator?,
            measurement: BodyKinematicsSequence<StandardDeviationTimedBodyKinematics>
        ) {
            generatedMeasurementListener?.onGeneratedMeasurement(
                this@GyroscopeMeasurementGeneratorProcessor,
                measurement
            )
        }

        override fun onReset(generator: GyroscopeMeasurementsGenerator?) {
            resetListener?.onReset(this@GyroscopeMeasurementGeneratorProcessor)
        }
    }

    /**
     * Internal measurements generator for gyroscope calibration.
     */
    override val measurementsGenerator =
        GyroscopeMeasurementsGenerator(measurementsGeneratorListener)

    /**
     * Sample used by internal measurement generator.
     */
    override val sample = TimedBodyKinematics()

    /**
     * Accelerometer sensor measurement expressed in NED coordinates.
     */
    private val nedAccelerometerMeasurement = AccelerometerSensorMeasurement()

    /**
     * Acceleration triad.
     */
    private val accelerationTriad = AccelerationTriad()

    /**
     * Body kinematics being reused for efficiency purposes.
     */
    private val kinematics = BodyKinematics()

    /**
     * Processes an accelerometer measurement to generate an instance of type [TimedBodyKinematics]
     * to be used by the internal measurement generator.
     * This method must be called along with [processGyroscopeMeasurement] to combine acceleration
     * information along with gyroscope information.
     *
     * @param measurement accelerometer sensor measurement.
     */
    override fun processAccelerometerData(
        measurement: AccelerometerSensorMeasurement,
        diffSeconds: Double,
        result: TimedBodyKinematics
    ) {
        // convert from device ENU coordinates to local plane NED coordinates
        measurement.toNed(nedAccelerometerMeasurement)
        // convert to triad taking into account measurement bias if available
        nedAccelerometerMeasurement.toTriad(accelerationTriad)

        // set accelerometer information (gyroscope information is filled on the corresponding
        // gyroscope processing method)
        kinematics.specificForceTriad = accelerationTriad

        result.kinematics = kinematics
        result.timestampSeconds = diffSeconds
    }

    /**
     * Estimates accumulated average and noise of gyroscope values during static periods.
     */
    private val gyroscopeAccumulatedNoiseEstimator =
        AccumulatedAngularSpeedTriadNoiseEstimator()

    /**
     * Gyroscope sensor measurement expressed in NED coordinates.
     */
    private val nedGyroscopeMeasurement = GyroscopeSensorMeasurement()

    /**
     * Angular speed triad.
     */
    private val angularSpeedTriad = AngularSpeedTriad()

    /**
     * Processes a gyroscope measurement.
     *
     * @param measurement gyroscope sensor measurement.
     */
    fun processGyroscopeMeasurement(
        measurement: GyroscopeSensorMeasurement
    ) {
        measurement.toNed(nedGyroscopeMeasurement)
        nedGyroscopeMeasurement.toTriad(angularSpeedTriad)

        // set gyroscope information
        kinematics.angularRateTriad = angularSpeedTriad

        if (status == Status.INITIALIZING) {
            gyroscopeAccumulatedNoiseEstimator.addTriad(angularSpeedTriad)
        }

        numberOfProcessedGyroscopeMeasurements++

        if (gyroscopeBaseNoiseLevel == null && (status == Status.INITIALIZATION_COMPLETED
                    || status == Status.STATIC_INTERVAL || status == Status.DYNAMIC_INTERVAL)) {
            gyroscopeBaseNoiseLevel =
                gyroscopeAccumulatedNoiseEstimator.standardDeviationNorm
        }
    }

    /**
     * Resets generator to its initial state.
     */
    override fun reset() {
        super.reset()
        numberOfProcessedGyroscopeMeasurements = 0
        gyroscopeBaseNoiseLevel = null
        gyroscopeAccumulatedNoiseEstimator.reset()
    }
}