/*
 * Copyright (C) 2025 Alberto Irurueta Carro (alberto@irurueta.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.irurueta.android.navigation.inertial.calibration.intervals.measurements

import android.content.Context
import com.irurueta.android.navigation.inertial.collectors.GyroscopeSensorCollector
import com.irurueta.android.navigation.inertial.collectors.SensorCollector
import com.irurueta.android.navigation.inertial.collectors.SensorDelay
import com.irurueta.android.navigation.inertial.collectors.measurements.AccelerometerSensorType
import com.irurueta.android.navigation.inertial.collectors.measurements.GyroscopeSensorMeasurement
import com.irurueta.android.navigation.inertial.collectors.measurements.GyroscopeSensorType
import com.irurueta.navigation.inertial.calibration.BodyKinematicsSequence
import com.irurueta.navigation.inertial.calibration.StandardDeviationTimedBodyKinematics
import com.irurueta.navigation.inertial.calibration.TimedBodyKinematics
import com.irurueta.navigation.inertial.calibration.generators.GyroscopeMeasurementsGenerator
import com.irurueta.navigation.inertial.calibration.generators.GyroscopeMeasurementsGeneratorListener
import com.irurueta.units.AngularSpeed

/**
 * Generates measurements that can later be used by gyroscope calibrators.
 * Measurements are generated by taking into account static and dynamic intervals on the device,
 * when the device is kept static (e.g. motionless), or when some force is applied to the device
 * changing its position or orientation.
 * Measurement generator converts device ENU measurements into measurements expressed in local
 * tangent plane NED coordinates.
 *
 * @property context Android context.
 * @property accelerometerSensorType One of the supported accelerometer sensor types.
 * @property accelerometerSensorDelay Delay of accelerometer sensor between samples.
 * @property gyroscopeSensorType One of the supported gyroscope sensor types.
 * @property gyroscopeSensorDelay Delay of gyroscope sensor between samples.
 * @property initializationStartedListener listener to notify when initialization starts.
 * @property initializationCompletedListener listener to notify when initialization successfully
 * completes.
 * @property errorListener listener to notify errors.
 * @property staticIntervalDetectedListener listener to notify when a static interval is detected.
 * @property dynamicIntervalDetectedListener listener to notify when a dynamic interval is detected.
 * @property staticIntervalSkippedListener listener to notify when a static interval is skipped if
 * its duration is too short.
 * @property dynamicIntervalSkippedListener listener to notify when a dynamic interval is skipped if
 * its duration is too long.
 * @property generatedMeasurementListener listener to notify when a new calibration measurement is
 * generated.
 * @property resetListener listener to notify when generator is restarted.
 */
class GyroscopeMeasurementGenerator(
    context: Context,
    accelerometerSensorType: AccelerometerSensorType =
        AccelerometerSensorType.ACCELEROMETER_UNCALIBRATED,
    accelerometerSensorDelay: SensorDelay = SensorDelay.FASTEST,
    val gyroscopeSensorType: GyroscopeSensorType = GyroscopeSensorType.GYROSCOPE_UNCALIBRATED,
    val gyroscopeSensorDelay: SensorDelay = SensorDelay.FASTEST,
    initializationStartedListener: OnInitializationStartedListener<GyroscopeMeasurementGenerator>? = null,
    initializationCompletedListener: OnInitializationCompletedListener<GyroscopeMeasurementGenerator>? = null,
    errorListener: OnErrorListener<GyroscopeMeasurementGenerator>? = null,
    staticIntervalDetectedListener: OnStaticIntervalDetectedListener<GyroscopeMeasurementGenerator>? = null,
    dynamicIntervalDetectedListener: OnDynamicIntervalDetectedListener<GyroscopeMeasurementGenerator>? = null,
    staticIntervalSkippedListener: OnStaticIntervalSkippedListener<GyroscopeMeasurementGenerator>? = null,
    dynamicIntervalSkippedListener: OnDynamicIntervalSkippedListener<GyroscopeMeasurementGenerator>? = null,
    generatedMeasurementListener: OnGeneratedMeasurementListener<GyroscopeMeasurementGenerator, BodyKinematicsSequence<StandardDeviationTimedBodyKinematics>>? = null,
    resetListener: OnResetListener<GyroscopeMeasurementGenerator>? = null
) : SingleSensorCalibrationMeasurementGenerator<
        GyroscopeMeasurementGenerator,
        GyroscopeMeasurementGeneratorProcessor,
        BodyKinematicsSequence<StandardDeviationTimedBodyKinematics>,
        GyroscopeMeasurementsGenerator,
        GyroscopeMeasurementsGeneratorListener,
        TimedBodyKinematics>(
    context,
    accelerometerSensorType,
    accelerometerSensorDelay,
    initializationStartedListener,
    initializationCompletedListener,
    errorListener,
    staticIntervalDetectedListener,
    dynamicIntervalDetectedListener,
    staticIntervalSkippedListener,
    dynamicIntervalSkippedListener,
    generatedMeasurementListener,
    resetListener
) {
    /**
     * Number of gyroscope measurements that have been processed.
     */
    val numberOfProcessedGyroscopeMeasurements: Int
        get() = processor.numberOfProcessedGyroscopeMeasurements

    /**
     * Gets gyroscope measurement base noise level that has been detected during initialization
     * expressed in radians per second (rad/s).
     * This is only available once generator completes initialization.
     */
    val gyroscopeBaseNoiseLevel: Double?
        get() = processor.gyroscopeBaseNoiseLevel

    /**
     * Gets gyroscope measurement base noise level that has been detected during initialization.
     * This is only available once generator completes initialization.
     */
    val gyroscopeBaseNoiseLevelAsMeasurement: AngularSpeed?
        get() = processor.gyroscopeBaseNoiseLevelAsMeasurement

    /**
     * Gets gyroscope measurement base noise level that has been detected during initialization.
     * This is only available once generator completes initialization.
     *
     * @param result instance where result will be stored.
     * @return true if result is available, false otherwise.
     */
    fun getGyroscopeBaseNoiseLevelAsMeasurement(result: AngularSpeed): Boolean {
        return processor.getGyroscopeBaseNoiseLevelAsMeasurement(result)
    }

    /**
     * Internal processor to process accelerometer and gyroscope sensor measurements.
     */
    override val processor = GyroscopeMeasurementGeneratorProcessor(
        initializationStartedListener = { _ ->
            initializationStartedListener?.onInitializationStarted(
                this
            )
        },
        initializationCompletedListener = { _, baseNoiseLevel ->
            initializationCompletedListener?.onInitializationCompleted(
                this,
                baseNoiseLevel
            )
        },
        errorListener = { _, reason -> errorListener?.onError(this, reason) },
        staticIntervalDetectedListener = { _ ->
            staticIntervalDetectedListener?.onStaticIntervalDetected(
                this
            )
        },
        dynamicIntervalDetectedListener = { _ ->
            dynamicIntervalDetectedListener?.onDynamicIntervalDetected(
                this
            )
        },
        staticIntervalSkippedListener = { _ ->
            staticIntervalSkippedListener?.onStaticIntervalSkipped(
                this
            )
        },
        dynamicIntervalSkippedListener = { _ ->
            dynamicIntervalSkippedListener?.onDynamicIntervalSkipped(
                this
            )
        },
        generatedMeasurementListener = { _, measurement ->
            generatedMeasurementListener?.onGeneratedMeasurement(
                this,
                measurement
            )
        },
        resetListener = { _ -> resetListener?.onReset(this) }
    )

    /**
     * Internal listener for gyroscope sensor collector.
     * Handles measurements collected by the gyroscope sensor so that they are processed
     * by the internal measurement generator.
     */
    private val gyroscopeCollectorMeasurementListener =
        SensorCollector.OnMeasurementListener<GyroscopeSensorMeasurement, GyroscopeSensorCollector> { _, measurement ->
            processor.processGyroscopeMeasurement(measurement)
        }

    /**
     * Listener to detect when accuracy of gyroscope sensor changes.
     * When sensor becomes unreliable, an error is notified.
     */
    private val gyroscopeAccuracyChangedListener =
        SensorCollector.OnAccuracyChangedListener<GyroscopeSensorMeasurement, GyroscopeSensorCollector> { _, accuracy ->
            processAccuracyChange(accuracy)
        }

    /**
     * Gyroscope sensor collector.
     * Collects gyroscope measurements.
     */
    private val gyroscopeCollector = GyroscopeSensorCollector(
        context,
        gyroscopeSensorType,
        gyroscopeSensorDelay,
        gyroscopeAccuracyChangedListener,
        gyroscopeCollectorMeasurementListener
    )

    /**
     * Gets gyroscope sensor being used to obtain measurements, or null if not available.
     * This can be used to obtain additional information about the sensor.
     */
    val gyroscopeSensor
        get() = gyroscopeCollector.sensor

    /**
     * Starts collection of sensor measurements.
     *
     * @throws IllegalStateException if detector is already running or sensor is not available.
     */
    @Throws(IllegalStateException::class)
    override fun start() {
        super.start()

        if (!gyroscopeCollector.start()) {
            stop()
            throw IllegalStateException("Unavailable gyroscope sensor")
        }
    }

    /**
     * Stops collection of sensor measurements.
     */
    override fun stop() {
        gyroscopeCollector.stop()
        super.stop()
    }
}