/*
 * Copyright (C) 2025 Alberto Irurueta Carro (alberto@irurueta.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.irurueta.android.navigation.inertial.calibration.intervals.measurements

import android.content.Context
import com.irurueta.android.navigation.inertial.collectors.MagnetometerSensorCollector
import com.irurueta.android.navigation.inertial.collectors.SensorCollector
import com.irurueta.android.navigation.inertial.collectors.SensorDelay
import com.irurueta.android.navigation.inertial.collectors.measurements.AccelerometerSensorType
import com.irurueta.android.navigation.inertial.collectors.measurements.MagnetometerSensorMeasurement
import com.irurueta.android.navigation.inertial.collectors.measurements.MagnetometerSensorType
import com.irurueta.navigation.inertial.BodyKinematicsAndMagneticFluxDensity
import com.irurueta.navigation.inertial.calibration.StandardDeviationBodyMagneticFluxDensity
import com.irurueta.navigation.inertial.calibration.generators.MagnetometerMeasurementsGenerator
import com.irurueta.navigation.inertial.calibration.generators.MagnetometerMeasurementsGeneratorListener
import com.irurueta.units.MagneticFluxDensity

/**
 * Generates measurements that can later be used by magnetometer calibrators.
 * Measurements are generated by taking into account static and dynamic intervals on the device,
 * when the device is kept static (e.g. motionless), or when same force is applied to the device
 * changing its position or orientation.
 * Measurement generator converts device ENU measurements into measurements expressed in local
 * tangent plane NED coordinates.
 *
 * @property context Android context.
 * @property accelerometerSensorType One of the supported accelerometer sensor types.
 * @property accelerometerSensorDelay Delay of accelerometer sensor between samples.
 * @property magnetometerSensorType One of the supported gyroscope sensor types.
 * @property magnetometerSensorDelay Delay of magnetometer sensor between samples.
 * @property initializationStartedListener listener to notify when initialization starts.
 * @property initializationCompletedListener listener to notify when initialization successfully
 * completes.
 * @property errorListener listener to notify errors.
 * @property staticIntervalDetectedListener listener to notify when a static interval is detected.
 * @property dynamicIntervalDetectedListener listener to notify when a dynamic interval is detected.
 * @property staticIntervalSkippedListener listener to notify when a static interval is skipped if
 * its duration is too short.
 * @property dynamicIntervalSkippedListener listener to notify when a dynamic interval is skipped if
 * its duration is too long.
 * @property generatedMeasurementListener listener to notify when a new calibration measurement is
 * generated.
 * @property resetListener listener to notify when generator is restarted.
 */
class MagnetometerMeasurementGenerator(
    context: Context,
    accelerometerSensorType: AccelerometerSensorType = AccelerometerSensorType.ACCELEROMETER_UNCALIBRATED,
    accelerometerSensorDelay: SensorDelay = SensorDelay.FASTEST,
    val magnetometerSensorType: MagnetometerSensorType =
        MagnetometerSensorType.MAGNETOMETER_UNCALIBRATED,
    val magnetometerSensorDelay: SensorDelay = SensorDelay.FASTEST,
    initializationStartedListener: OnInitializationStartedListener<MagnetometerMeasurementGenerator>? = null,
    initializationCompletedListener: OnInitializationCompletedListener<MagnetometerMeasurementGenerator>? = null,
    errorListener: OnErrorListener<MagnetometerMeasurementGenerator>? = null,
    staticIntervalDetectedListener: OnStaticIntervalDetectedListener<MagnetometerMeasurementGenerator>? = null,
    dynamicIntervalDetectedListener: OnDynamicIntervalDetectedListener<MagnetometerMeasurementGenerator>? = null,
    staticIntervalSkippedListener: OnStaticIntervalSkippedListener<MagnetometerMeasurementGenerator>? = null,
    dynamicIntervalSkippedListener: OnDynamicIntervalSkippedListener<MagnetometerMeasurementGenerator>? = null,
    generatedMeasurementListener: OnGeneratedMeasurementListener<MagnetometerMeasurementGenerator, StandardDeviationBodyMagneticFluxDensity>? = null,
    resetListener: OnResetListener<MagnetometerMeasurementGenerator>? = null,
) : SingleSensorCalibrationMeasurementGenerator<
        MagnetometerMeasurementGenerator,
        MagnetometerMeasurementGeneratorProcessor,
        StandardDeviationBodyMagneticFluxDensity,
        MagnetometerMeasurementsGenerator,
        MagnetometerMeasurementsGeneratorListener,
        BodyKinematicsAndMagneticFluxDensity>(
    context,
    accelerometerSensorType,
    accelerometerSensorDelay,
    initializationStartedListener,
    initializationCompletedListener,
    errorListener,
    staticIntervalDetectedListener,
    dynamicIntervalDetectedListener,
    staticIntervalSkippedListener,
    dynamicIntervalSkippedListener,
    generatedMeasurementListener,
    resetListener
) {
    /**
     * Number of magnetometer measurements that have been processed.
     */
    val numberOfProcessedMagnetometerMeasurements: Int
        get() = processor.numberOfProcessedMagnetometerMeasurements

    /**
     * Gets magnetometer measurement base noise level that has been detected during initialization
     * expressed in Teslas (T).
     * This is only available once generator completes initialization.
     */
    val magnetometerBaseNoiseLevel: Double?
        get() = processor.magnetometerBaseNoiseLevel

    /**
     * Gets magnetometer measurement base noise level that has been detected during initialization.
     * This is only available once generator completes initialization.
     */
    val magnetometerBaseNoiseLevelAsMeasurement: MagneticFluxDensity?
        get() = processor.magnetometerBaseNoiseLevelAsMeasurement

    /**
     * Gets magnetometer measurement base noise level that has been detected during initialization.
     * This is only available once generator completes initialization.
     *
     * @param result instance where result will be stored.
     * @return true if result is available, false otherwise.
     */
    fun getMagnetometerBaseNoiseLevelAsMeasurement(result: MagneticFluxDensity): Boolean {
        return processor.getMagnetometerBaseNoiseLevelAsMeasurement(result)
    }

    /**
     * Norm of average magnetic flux density obtained during initialization and expressed in
     * Teslas (T).
     * This is only available once generator completes initialization.
     */
    val initialMagneticFluxDensityNorm: Double?
        get() = processor.initialMagneticFluxDensityNorm

    /**
     * Gets norm of average magnetic flux density obtained during initialization.
     * This is only available once generator completes initialization.
     */
    val initialMagneticFluxDensityNormAsMeasurement: MagneticFluxDensity?
        get() = processor.initialMagneticFluxDensityNormAsMeasurement

    /**
     * Gets norm of average magnetic flux density obtained during initialization.
     * This is only available once generator completes initialization.
     *
     * @param result instance where result will be stored.
     * @return true if result is available, false otherwise.
     */
    fun getInitialMagneticFluxDensityNormAsMeasurement(result: MagneticFluxDensity): Boolean {
        return processor.getInitialMagneticFluxDensityNormAsMeasurement(result)
    }

    /**
     * Internal processor to process accelerometer and magnetometer sensor measurements.
     */
    override val processor = MagnetometerMeasurementGeneratorProcessor(
        initializationStartedListener = { _ ->
            initializationStartedListener?.onInitializationStarted(
                this
            )
        },
        initializationCompletedListener = { _, baseNoiseLevel ->
            initializationCompletedListener?.onInitializationCompleted(
                this,
                baseNoiseLevel
            )
        },
        errorListener = { _, reason -> errorListener?.onError(this, reason) },
        staticIntervalDetectedListener = { _ ->
            staticIntervalDetectedListener?.onStaticIntervalDetected(
                this
            )
        },
        dynamicIntervalDetectedListener = { _ ->
            dynamicIntervalDetectedListener?.onDynamicIntervalDetected(
                this
            )
        },
        staticIntervalSkippedListener = { _ ->
            staticIntervalSkippedListener?.onStaticIntervalSkipped(
                this
            )
        },
        dynamicIntervalSkippedListener = { _ ->
            dynamicIntervalSkippedListener?.onDynamicIntervalSkipped(
                this
            )
        },
        generatedMeasurementListener = { _, measurement ->
            generatedMeasurementListener?.onGeneratedMeasurement(
                this,
                measurement
            )
        },
        resetListener = { _ -> resetListener?.onReset(this) }
    )

    /**
     * Internal listener for magnetometer sensor collector.
     * Handles measurements collected by the magnetometer sensor so that they are processed
     * by the internal measurement generator.
     */
    private val magnetometerCollectorMeasurementListener =
        SensorCollector.OnMeasurementListener<MagnetometerSensorMeasurement, MagnetometerSensorCollector> { _, measurement ->
            processor.processMagnetometerMeasurement(measurement)
        }

    /**
     * Listener to detect when accuracy of magnetometer sensor changes.
     * When sensor becomes unreliable, an error is notified.
     */
    private val magnetometerAccuracyChangedListener =
        SensorCollector.OnAccuracyChangedListener<MagnetometerSensorMeasurement, MagnetometerSensorCollector> { _, accuracy ->
            processAccuracyChange(accuracy)
        }

    /**
     * Magnetometer sensor collector.
     * Collects magnetometer measurements.
     */
    private val magnetometerCollector = MagnetometerSensorCollector(
        context,
        magnetometerSensorType,
        magnetometerSensorDelay,
        magnetometerAccuracyChangedListener,
        magnetometerCollectorMeasurementListener
    )

    /**
     * Gets magnetometer sensor being used to obtain measurements, or null if not available.
     * This can be used to obtain additional information about the sensor.
     */
    val magnetometerSensor
        get() = magnetometerCollector.sensor

    /**
     * Starts collection of sensor measurements.
     *
     * @throws IllegalStateException if detector is already running or sensor is not available.
     */
    @Throws(IllegalStateException::class)
    override fun start() {
        super.start()

        if (!magnetometerCollector.start()) {
            stop()
            throw IllegalStateException("Unavailable magnetometer sensor")
        }
    }

    /**
     * Stops collection of sensor measurements.
     */
    override fun stop() {
        magnetometerCollector.stop()
        super.stop()
    }
}