/*
 * Copyright (C) 2025 Alberto Irurueta Carro (alberto@irurueta.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.irurueta.android.navigation.inertial.calibration.intervals.measurements

import com.irurueta.android.navigation.inertial.calibration.intervals.Status
import com.irurueta.android.navigation.inertial.collectors.measurements.AccelerometerSensorMeasurement
import com.irurueta.android.navigation.inertial.collectors.measurements.MagnetometerSensorMeasurement
import com.irurueta.navigation.inertial.BodyKinematics
import com.irurueta.navigation.inertial.BodyKinematicsAndMagneticFluxDensity
import com.irurueta.navigation.inertial.BodyMagneticFluxDensity
import com.irurueta.navigation.inertial.calibration.AccelerationTriad
import com.irurueta.navigation.inertial.calibration.MagneticFluxDensityTriad
import com.irurueta.navigation.inertial.calibration.StandardDeviationBodyMagneticFluxDensity
import com.irurueta.navigation.inertial.calibration.TimedBodyKinematics
import com.irurueta.navigation.inertial.calibration.generators.MagnetometerMeasurementsGenerator
import com.irurueta.navigation.inertial.calibration.generators.MagnetometerMeasurementsGeneratorListener
import com.irurueta.navigation.inertial.calibration.intervals.TriadStaticIntervalDetector
import com.irurueta.navigation.inertial.calibration.noise.AccumulatedMagneticFluxDensityTriadNoiseEstimator
import com.irurueta.units.MagneticFluxDensity
import com.irurueta.units.MagneticFluxDensityUnit

/**
 * Generates measurements that can later be used by magnetometer calibrators.
 * Measurements are generated by taking into account static and dynamic intervals on the device,
 * when the device is kept static (e.g. motionless), or when same force is applied to the device
 * changing its position or orientation.
 * Measurement generator converts device ENU measurements into measurements expressed in local
 * tangent plane NED coordinates.
 *
 * @param initializationStartedListener listener to notify when initialization starts.
 * @property initializationCompletedListener listener to notify when initialization successfully
 * completes.
 * @property errorListener listener to notify errors.
 * @property staticIntervalDetectedListener listener to notify when a static interval is detected.
 * @property dynamicIntervalDetectedListener listener to notify when a dynamic interval is detected.
 * @property staticIntervalSkippedListener listener to notify when a static interval is skipped if
 * its duration is too short.
 * @property dynamicIntervalSkippedListener listener to notify when a dynamic interval is skipped if
 * its duration is too long.
 * @property generatedMeasurementListener listener to notify when a new calibration measurement is
 * generated.
 * @property resetListener listener to notify when generator is restarted.
 */
class MagnetometerMeasurementGeneratorProcessor(
    initializationStartedListener: OnInitializationStartedListener<MagnetometerMeasurementGeneratorProcessor>? = null,
    initializationCompletedListener: OnInitializationCompletedListener<MagnetometerMeasurementGeneratorProcessor>? = null,
    errorListener: OnErrorListener<MagnetometerMeasurementGeneratorProcessor>? = null,
    staticIntervalDetectedListener: OnStaticIntervalDetectedListener<MagnetometerMeasurementGeneratorProcessor>? = null,
    dynamicIntervalDetectedListener: OnDynamicIntervalDetectedListener<MagnetometerMeasurementGeneratorProcessor>? = null,
    staticIntervalSkippedListener: OnStaticIntervalSkippedListener<MagnetometerMeasurementGeneratorProcessor>? = null,
    dynamicIntervalSkippedListener: OnDynamicIntervalSkippedListener<MagnetometerMeasurementGeneratorProcessor>? = null,
    generatedMeasurementListener: OnGeneratedMeasurementListener<MagnetometerMeasurementGeneratorProcessor, StandardDeviationBodyMagneticFluxDensity>? = null,
    resetListener: OnResetListener<MagnetometerMeasurementGeneratorProcessor>? = null
) : SingleSensorCalibrationMeasurementGeneratorProcessor<MagnetometerMeasurementGeneratorProcessor,
        StandardDeviationBodyMagneticFluxDensity,
        MagnetometerMeasurementsGenerator,
        MagnetometerMeasurementsGeneratorListener,
        BodyKinematicsAndMagneticFluxDensity>(
    initializationStartedListener,
    initializationCompletedListener,
    errorListener,
    staticIntervalDetectedListener,
    dynamicIntervalDetectedListener,
    staticIntervalSkippedListener,
    dynamicIntervalSkippedListener,
    generatedMeasurementListener,
    resetListener
) {
    /**
     * Number of magnetometer measurements that have been processed.
     */
    var numberOfProcessedMagnetometerMeasurements: Int = 0
        private set

    /**
     * Gets magnetometer measurement base noise level that has been detected during initialization
     * expressed in Teslas (T).
     * This is only available once generator completes initialization.
     */
    var magnetometerBaseNoiseLevel: Double? = null
        private set

    /**
     * Gets magnetometer measurement base noise level that has been detected during initialization.
     * This is only available once generator completes initialization.
     */
    val magnetometerBaseNoiseLevelAsMeasurement: MagneticFluxDensity?
        get() {
            val value = magnetometerBaseNoiseLevel ?: return null
            return MagneticFluxDensity(value, MagneticFluxDensityUnit.TESLA)
        }

    /**
     * Gets magnetometer measurement base noise level that has been detected during initialization.
     * This is only available once generator completes initialization.
     *
     * @param result instance where result will be stored.
     * @return true if result is available, false otherwise.
     */
    fun getMagnetometerBaseNoiseLevelAsMeasurement(result: MagneticFluxDensity): Boolean {
        val value = magnetometerBaseNoiseLevel ?: return false
        result.value = value
        result.unit = MagneticFluxDensityUnit.TESLA
        return true
    }

    /**
     * Norm of average magnetic flux density obtained during initialization and expressed in
     * Teslas (T).
     * This is only available once generator completes initialization.
     */
    var initialMagneticFluxDensityNorm: Double? = null
        private set

    /**
     * Gets norm of average magnetic flux density obtained during initialization.
     * This is only available once generator completes initialization.
     */
    val initialMagneticFluxDensityNormAsMeasurement: MagneticFluxDensity?
        get() {
            val value = initialMagneticFluxDensityNorm ?: return null
            return MagneticFluxDensity(value, MagneticFluxDensityUnit.TESLA)
        }

    /**
     * Gets norm of average magnetic flux density obtained during initialization.
     * This is only available once generator completes initialization.
     *
     * @param result instance where result will be stored.
     * @return true if result is available, false otherwise.
     */
    fun getInitialMagneticFluxDensityNormAsMeasurement(result: MagneticFluxDensity): Boolean {
        val value = initialMagneticFluxDensityNorm ?: return false
        result.value = value
        result.unit = MagneticFluxDensityUnit.TESLA
        return true
    }

    /**
     * Listener for internal measurement generator.
     */
    override val measurementsGeneratorListener =
        object : MagnetometerMeasurementsGeneratorListener {
            override fun onInitializationStarted(generator: MagnetometerMeasurementsGenerator?) {
                initializationStartedListener?.onInitializationStarted(
                    this@MagnetometerMeasurementGeneratorProcessor
                )
            }

            override fun onInitializationCompleted(
                generator: MagnetometerMeasurementsGenerator?,
                baseNoiseLevel: Double
            ) {
                initializationCompletedListener?.onInitializationCompleted(
                    this@MagnetometerMeasurementGeneratorProcessor,
                    baseNoiseLevel
                )
            }

            override fun onError(
                generator: MagnetometerMeasurementsGenerator?,
                reason: TriadStaticIntervalDetector.ErrorReason
            ) {
                errorListener?.onError(
                    this@MagnetometerMeasurementGeneratorProcessor,
                    mapErrorReason(reason)
                )
            }

            override fun onStaticIntervalDetected(generator: MagnetometerMeasurementsGenerator?) {
                staticIntervalDetectedListener?.onStaticIntervalDetected(
                    this@MagnetometerMeasurementGeneratorProcessor
                )
            }

            override fun onDynamicIntervalDetected(generator: MagnetometerMeasurementsGenerator?) {
                dynamicIntervalDetectedListener?.onDynamicIntervalDetected(
                    this@MagnetometerMeasurementGeneratorProcessor
                )
            }

            override fun onStaticIntervalSkipped(generator: MagnetometerMeasurementsGenerator?) {
                staticIntervalSkippedListener?.onStaticIntervalSkipped(
                    this@MagnetometerMeasurementGeneratorProcessor
                )
            }

            override fun onDynamicIntervalSkipped(generator: MagnetometerMeasurementsGenerator?) {
                dynamicIntervalSkippedListener?.onDynamicIntervalSkipped(
                    this@MagnetometerMeasurementGeneratorProcessor
                )
            }

            override fun onGeneratedMeasurement(
                generator: MagnetometerMeasurementsGenerator?,
                measurement: StandardDeviationBodyMagneticFluxDensity
            ) {
                generatedMeasurementListener?.onGeneratedMeasurement(
                    this@MagnetometerMeasurementGeneratorProcessor,
                    measurement
                )
            }

            override fun onReset(generator: MagnetometerMeasurementsGenerator?) {
                resetListener?.onReset(this@MagnetometerMeasurementGeneratorProcessor)
            }
        }

    /**
     * Internal measurements generator for magnetometer calibration.
     */
    override val measurementsGenerator =
        MagnetometerMeasurementsGenerator(measurementsGeneratorListener)

    /**
     * Sample used by internal measurement generator.
     */
    override val sample = BodyKinematicsAndMagneticFluxDensity()

    /**
     * Accelerometer sensor measurement expressed in NED coordinates.
     */
    private val nedAccelerometerMeasurement = AccelerometerSensorMeasurement()

    /**
     * Acceleration triad.
     */
    private val accelerationTriad = AccelerationTriad()

    /**
     * Body kinematics being reused for efficiency purposes.
     */
    private val kinematics = BodyKinematics()

    /**
     * Body magnetic flux density being reused for efficiency purposes.
     */
    private val magneticFluxDensity = BodyMagneticFluxDensity()

    /**
     * Processes an accelerometer measurement to generate an instance of type [TimedBodyKinematics]
     * to be used by the internal measurement generator.
     * This method must be called along with [processMagnetometerMeasurement] to combine acceleration
     * information along with gyroscope information.
     *
     * @param measurement accelerometer sensor measurement.
     */
    override fun processAccelerometerData(
        measurement: AccelerometerSensorMeasurement,
        diffSeconds: Double,
        result: BodyKinematicsAndMagneticFluxDensity
    ) {
        // convert from device ENU coordinates to local plane NED coordinates
        measurement.toNed(nedAccelerometerMeasurement)
        // convert to triad taking into account measurement bias if available
        nedAccelerometerMeasurement.toTriad(accelerationTriad)

        // set accelerometer information (gyroscope information is filled on the corresponding
        // gyroscope processing method)
        kinematics.specificForceTriad = accelerationTriad
        result.kinematics = kinematics

        // set magnetometer information
        result.magneticFluxDensity = magneticFluxDensity
    }

    /**
     * Estimates accumulated average and noise of magnetometer values during static periods.
     */
    private val magnetometerAccumulatedNoiseEstimator =
        AccumulatedMagneticFluxDensityTriadNoiseEstimator()

    /**
     * Magnetometer sensor measurement expressed in NED coordinates.
     */
    private val nedMagnetometerMeasurement = MagnetometerSensorMeasurement()

    /**
     * Magnetic flux density triad.
     */
    private val magneticFluxDensityTriad = MagneticFluxDensityTriad()

    /**
     * Processes a magnetometer measurement.
     *
     * @param measurement magnetometer sensor measurement.
     */
    fun processMagnetometerMeasurement(
        measurement: MagnetometerSensorMeasurement
    ) {
        measurement.toNed(nedMagnetometerMeasurement)
        nedMagnetometerMeasurement.toTriad(magneticFluxDensityTriad)

        magneticFluxDensity.setCoordinates(magneticFluxDensityTriad)

        if (status == Status.INITIALIZING) {
            magnetometerAccumulatedNoiseEstimator.addTriad(magneticFluxDensityTriad)
        }

        numberOfProcessedMagnetometerMeasurements++

        if (magnetometerBaseNoiseLevel == null && (status == Status.INITIALIZATION_COMPLETED
                    || status == Status.STATIC_INTERVAL || status == Status.DYNAMIC_INTERVAL)
        ) {
            magnetometerBaseNoiseLevel =
                magnetometerAccumulatedNoiseEstimator.standardDeviationNorm
            initialMagneticFluxDensityNorm = magnetometerAccumulatedNoiseEstimator.avgNorm
        }
    }

    /**
     * Resets generator to its initial state.
     */
    override fun reset() {
        super.reset()
        numberOfProcessedMagnetometerMeasurements = 0
        magnetometerBaseNoiseLevel = null
        initialMagneticFluxDensityNorm = null
        magnetometerAccumulatedNoiseEstimator.reset()
    }
}