/*
 * Copyright (C) 2025 Alberto Irurueta Carro (alberto@irurueta.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.irurueta.android.navigation.inertial.calibration.intervals.measurements

import android.content.Context
import com.irurueta.android.navigation.inertial.calibration.intervals.ErrorReason
import com.irurueta.android.navigation.inertial.collectors.SensorDelay
import com.irurueta.android.navigation.inertial.collectors.measurements.AccelerometerSensorType
import com.irurueta.navigation.inertial.calibration.generators.MeasurementsGenerator
import com.irurueta.navigation.inertial.calibration.generators.MeasurementsGeneratorListener

/**
 * Base class to generate measurements for a single sensor that can later be used by calibrators
 * of such sensor.
 * Measurements are generated by taking into account static and dynamic intervals on the device,
 * where the device is kept static (e.g. motionless), or where some force is applied to the device
 * changing its position or orientation.
 * Static and dynamic intervals are measured using the only sensor used by the generator.
 * Measurement generator converts device ENU measurements into measurements expressed in local
 * tangent plane NED coordinates.
 *
 * @property context Android context.
 * @property accelerometerSensorType One of the supported accelerometer sensor types.
 * @property accelerometerSensorDelay Delay of sensor between samples.
 * @property initializationStartedListener listener to notify when initialization starts.
 * @property initializationCompletedListener listener to notify when initialization successfully
 * completes.
 * @property errorListener listener to notify errors.
 * @property staticIntervalDetectedListener listener to notify when a static interval is detected.
 * @property dynamicIntervalDetectedListener listener to notify when a dynamic interval is detected.
 * @property staticIntervalSkippedListener listener to notify when a static interval is skipped if
 * its duration is too short.
 * @property dynamicIntervalSkippedListener listener to notify when a dynamic interval is skipped if
 * its duration is too long.
 * @property generatedMeasurementListener listener to notify when a new calibration measurement is
 * generated.
 * @property resetListener listener to notify when generator is restarted.
 * @param C type of [SingleSensorCalibrationMeasurementGenerator]
 * @param P type of internal [SingleSensorCalibrationMeasurementGeneratorProcessor]
 * @param T type of measurement to be generated.
 * @param G type of internal generator.
 * @param L type of listener.
 * @param I type of input data to be processed.
 */
abstract class SingleSensorCalibrationMeasurementGenerator<
        C : SingleSensorCalibrationMeasurementGenerator<C, P, T, G, L, I>,
        P : SingleSensorCalibrationMeasurementGeneratorProcessor<P, T, G, L, I>,
        T,
        G : MeasurementsGenerator<T, G, L, I>,
        L : MeasurementsGeneratorListener<T, G, L, I>,
        I>(
    context: Context,
    accelerometerSensorType: AccelerometerSensorType = AccelerometerSensorType.ACCELEROMETER_UNCALIBRATED,
    accelerometerSensorDelay: SensorDelay = SensorDelay.FASTEST,
    var initializationStartedListener: OnInitializationStartedListener<C>? = null,
    var initializationCompletedListener: OnInitializationCompletedListener<C>? = null,
    var errorListener: OnErrorListener<C>? = null,
    var staticIntervalDetectedListener: OnStaticIntervalDetectedListener<C>? = null,
    var dynamicIntervalDetectedListener: OnDynamicIntervalDetectedListener<C>? = null,
    var staticIntervalSkippedListener: OnStaticIntervalSkippedListener<C>? = null,
    var dynamicIntervalSkippedListener: OnDynamicIntervalSkippedListener<C>? = null,
    var generatedMeasurementListener: OnGeneratedMeasurementListener<C, T>? = null,
    var resetListener: OnResetListener<C>? = null
) : CalibrationMeasurementGenerator<I, P>(
    context,
    accelerometerSensorType,
    accelerometerSensorDelay
) {

    /**
     * Notifies that sensor has become unreliable.
     */
    @Suppress("UNCHECKED_CAST")
    override fun notifyUnreliableSensor() {
        errorListener?.onError(
            this@SingleSensorCalibrationMeasurementGenerator as C,
            ErrorReason.UNRELIABLE_SENSOR
        )
    }

    /**
     * Starts collection of sensor measurements.
     *
     * @throws IllegalStateException if generator is already running or sensor is not available.
     */
    @Throws(IllegalStateException::class)
    override fun start() {
        check(!running)

        reset()

        running = true
        if (!accelerometerCollector.start()) {
            running = false
            throw IllegalStateException("Unavailable accelerometer sensor")
        }
    }

    /**
     * Stops collection of sensor measurements.
     */
    override fun stop() {
        accelerometerCollector.stop()
        running = false
    }

    /**
     * Resets generator to its initial state.
     */
    protected fun reset() {
       processor.reset()
    }

    /**
     * Interface to notify when generator starts initialization.
     *
     * @param C an implementation of [SingleSensorCalibrationMeasurementGenerator].
     */
    fun interface OnInitializationStartedListener<C : SingleSensorCalibrationMeasurementGenerator<C, *, *, *, *, *>> {

        /**
         * Called when initial static period starts so that base noise level starts being estimated.
         *
         * @param generator generator that raised the event.
         */
        fun onInitializationStarted(generator: C)
    }

    /**
     * Interface to notify when generator completes its initialization.
     *
     * @param C an implementation of [SingleSensorCalibrationMeasurementGenerator]
     */
    fun interface OnInitializationCompletedListener<C : SingleSensorCalibrationMeasurementGenerator<C, *, *, *, *, *>> {
        /**
         * Called when initial static period successfully completes and accelerometer base noise
         * level is estimated so that static and dynamic periods can be detected.
         *
         * @param generator generator that raised the event.
         * @param baseNoiseLevel base measurement noise level expressed in meters per squared second
         * (m/s^2).
         */
        fun onInitializationCompleted(generator: C, baseNoiseLevel: Double)
    }

    /**
     * Interface to notify when an error occurs.
     *
     * @param C an implementation of [SingleSensorCalibrationMeasurementGenerator]
     */
    fun interface OnErrorListener<C : SingleSensorCalibrationMeasurementGenerator<C, *, *, *, *, *>> {
        /**
         * Called when an error is detected, either at initialization because excessive changes in
         * sensor measurements are found, or because sensor becomes unreliable.
         * When an error occurs, generator is stopped and needs to be restarted to be used again.
         *
         * @param generator generator that raised the event.
         * @param reason reason why error was detected.
         */
        fun onError(generator: C, reason: ErrorReason)
    }

    /**
     * Interface to notify that a new static interval is detected.
     *
     * @param C an implementation of [SingleSensorCalibrationMeasurementGenerator]
     */
    fun interface OnStaticIntervalDetectedListener<C : SingleSensorCalibrationMeasurementGenerator<C, *, *, *, *, *>> {
        /**
         * Called when a static interval has been detected after initialization.
         *
         * @param generator generator that raised the event.
         */
        fun onStaticIntervalDetected(generator: C)
    }

    /**
     * Interface to notify when a dynamic interval is detected.
     *
     * @param C an implementation of [SingleSensorCalibrationMeasurementGenerator]
     */
    fun interface OnDynamicIntervalDetectedListener<C : SingleSensorCalibrationMeasurementGenerator<C, *, *, *, *, *>> {
        /**
         * Called when a dynamic interval has been detected after initialization.
         *
         * @param generator generator that raised the event.
         */
        fun onDynamicIntervalDetected(generator: C)
    }

    /**
     * Interface to notify when a static interval is skipped.
     * This happens when interval is too short.
     *
     * @param C an implementation of [SingleSensorCalibrationMeasurementGenerator]
     */
    fun interface OnStaticIntervalSkippedListener<C : SingleSensorCalibrationMeasurementGenerator<C, *, *, *, *, *>> {
        /**
         * Called when a detected static interval is skipped because there are not enough samples to
         * be processed.
         *
         * @param generator generator that raised the event.
         */
        fun onStaticIntervalSkipped(generator: C)
    }

    /**
     * Interface to notify when a dynamic interval is skipped.
     * This happens when interval is too long.
     *
     * @param C an implementation of [SingleSensorCalibrationMeasurementGenerator]
     */
    fun interface OnDynamicIntervalSkippedListener<C : SingleSensorCalibrationMeasurementGenerator<C, *, *, *, *, *>> {
        /**
         * Called when a detected dynamic interval is skipped because it has too many samples in it.
         *
         * @param generator generator that raised the event.
         */
        fun onDynamicIntervalSkipped(generator: C)
    }

    /**
     * Interface to notify when a new calibration measurement is generated.
     *
     * @param C an implementation of [SingleSensorCalibrationMeasurementGenerator]
     * @param T type of measurement to be generated.
     */
    fun interface OnGeneratedMeasurementListener<C : SingleSensorCalibrationMeasurementGenerator<C, *, T, *, *, *>, T> {
        /**
         * Called when a new calibration measurement is generated.
         *
         * @param generator generator that raised the event.
         * @param measurement generated calibration measurement.
         */
        fun onGeneratedMeasurement(generator: C, measurement: T)
    }

    /**
     * Interface to notify when generator is reset (occurs when starting after stopping the
     * generator)
     *
     * @param C an implementation of [SingleSensorCalibrationMeasurementGenerator]
     */
    fun interface OnResetListener<C : SingleSensorCalibrationMeasurementGenerator<C, *, *, *, *, *>> {
        /**
         * Called when generator is reset.
         *
         * @param generator generator that raised the event.
         */
        fun onReset(generator: C)
    }
}