/*
 * Copyright (C) 2025 Alberto Irurueta Carro (alberto@irurueta.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.irurueta.android.navigation.inertial.calibration.intervals.measurements

import com.irurueta.android.navigation.inertial.calibration.intervals.ErrorReason
import com.irurueta.android.navigation.inertial.calibration.intervals.Status
import com.irurueta.navigation.inertial.calibration.generators.MeasurementsGenerator
import com.irurueta.navigation.inertial.calibration.generators.MeasurementsGeneratorListener
import com.irurueta.navigation.inertial.calibration.intervals.TriadStaticIntervalDetector
import com.irurueta.units.Acceleration

/**
 * Base class to generate measurements for a single sensor that can later be used by calibrators
 * of such sensor.
 * Measurements are generated by taking into account static and dynamic intervals on the device,
 * where the device is kept static (e.g. motionless), or where some force is applied to the device
 * changing its position or orientation.
 * Static and dynamic intervals are measured using the only sensor used by the generator.
 * Measurement generator converts device ENU measurements into measurements expressed in local
 * tangent plane NED coordinates.
 *
 * @property initializationStartedListener listener to notify when initialization starts.
 * @property initializationCompletedListener listener to notify when initialization successfully
 * completes.
 * @property errorListener listener to notify errors.
 * @property staticIntervalDetectedListener listener to notify when a static interval is detected.
 * @property dynamicIntervalDetectedListener listener to notify when a dynamic interval is detected.
 * @property staticIntervalSkippedListener listener to notify when a static interval is skipped if
 * its duration is too short.
 * @property dynamicIntervalSkippedListener listener to notify when a dynamic interval is skipped if
 * its duration is too long.
 * @property generatedMeasurementListener listener to notify when a new calibration measurement is
 * generated.
 * @property resetListener listener to notify when generator is restarted.
 * @param T type of measurement to be generated.
 * @param G type of internal generator.
 * @param L type of listener.
 * @param I type of input data to be processed.
 */
abstract class SingleSensorCalibrationMeasurementGeneratorProcessor<
        P : SingleSensorCalibrationMeasurementGeneratorProcessor<P, T, G, L, I>,
        T,
        G : MeasurementsGenerator<T, G, L, I>,
        L : MeasurementsGeneratorListener<T, G, L, I>,
        I>(
            var initializationStartedListener: OnInitializationStartedListener<P>? = null,
            var initializationCompletedListener: OnInitializationCompletedListener<P>? = null,
            var errorListener: OnErrorListener<P>? = null,
            var staticIntervalDetectedListener: OnStaticIntervalDetectedListener<P>? = null,
            var dynamicIntervalDetectedListener: OnDynamicIntervalDetectedListener<P>? = null,
            var staticIntervalSkippedListener: OnStaticIntervalSkippedListener<P>? = null,
            var dynamicIntervalSkippedListener: OnDynamicIntervalSkippedListener<P>? = null,
            var generatedMeasurementListener: OnGeneratedMeasurementListener<P, T>? = null,
            var resetListener: OnResetListener<P>? = null
        ) : CalibrationMeasurementGeneratorProcessor<I>() {

    /**
     * Listener for internal measurement generator.
     */
    protected abstract val measurementsGeneratorListener: L

    /**
     * Internal measurements generator for calibration.
     */
    protected abstract val measurementsGenerator: G

    /**
     * Processes sample in internal measurements generator.
     */
    override fun processSampleInInternalGenerator() {
        measurementsGenerator.process(sample)
    }

    /**
     * Updates time interval of internal generator once the interval detector has been initialized.
     */
    override fun updateTimeIntervalOfInternalGenerator() {
        measurementsGenerator.timeInterval =
            accelerometerTimeIntervalEstimator.averageTimeInterval
    }

    /**
     * Gets or sets minimum number of samples required in a static interval to be taken into
     * account. Smaller static intervals will be discarded.
     *
     * @throws IllegalArgumentException if provided value is less than 2.
     */
    override var minStaticSamples
        get() = measurementsGenerator.minStaticSamples
        @Throws(IllegalArgumentException::class)
        set(value) {
            measurementsGenerator.minStaticSamples = value
        }

    /**
     * Gets or sets maximum number of samples allowed in dynamic intervals.
     * Dynamic intervals exceeding this value are discarded.
     *
     * @throws IllegalArgumentException if provided value is less than 2.
     */
    override var maxDynamicSamples
        get() = measurementsGenerator.maxDynamicSamples
        @Throws(IllegalArgumentException::class)
        set(value) {
            measurementsGenerator.maxDynamicSamples = value
        }

    /**
     * Gets or sets length of number of samples to keep within the window being processed to
     * determine instantaneous sensor noise level. Window size must always be larger than
     * allowed minimum value, which is 2 and must have an odd value.
     *
     * @throws IllegalArgumentException if provided value is not valid.
     */
    override var windowSize
        get() = measurementsGenerator.windowSize
        @Throws(IllegalArgumentException::class)
        set(value) {
            measurementsGenerator.windowSize = value
        }

    /**
     * Gets or sets number of samples to be processed initially while keeping the sensor static in
     * order to find the base noise level when device is static.
     *
     * @throws IllegalArgumentException if provided value is less than
     * [TriadStaticIntervalDetector.MINIMUM_INITIAL_STATIC_SAMPLES].
     */
    override var initialStaticSamples
        get() = measurementsGenerator.initialStaticSamples
        @Throws(IllegalArgumentException::class)
        set(value) {
            measurementsGenerator.initialStaticSamples = value
        }

    /**
     * Gets or sets factor to be applied to detected base noise level in order to determine
     * threshold for static/dynamic period changes. This factor is unit-less.
     *
     * @throws IllegalArgumentException if provided value is zero or negative
     */
    override var thresholdFactor
        get() = measurementsGenerator.thresholdFactor
        @Throws(IllegalArgumentException::class)
        set(value) {
            measurementsGenerator.thresholdFactor = value
        }

    /**
     * Gets or sets factor to determine that a sudden movement has occurred during initialization if
     * instantaneous noise level exceeds accumulated noise level by this factor amount. This factor
     * is unit-less.
     *
     * @throws IllegalArgumentException if provided value is zero or negative.
     */
    override var instantaneousNoiseLevelFactor
        get() = measurementsGenerator.instantaneousNoiseLevelFactor
        @Throws(IllegalArgumentException::class)
        set(value) {
            measurementsGenerator.instantaneousNoiseLevelFactor = value
        }

    /**
     * Gets or sets overall absolute threshold to determine whether there has been excessive motion
     * during the whole initialization phase. Failure will be detected if estimated base noise level
     * exceeds this threshold when initialization completes. This threshold is expressed in meters
     * per squared second (m/s^2).
     *
     * @throws IllegalArgumentException if provided value is zero or negative.
     */
    override var baseNoiseLevelAbsoluteThreshold
        get() = measurementsGenerator.baseNoiseLevelAbsoluteThreshold
        @Throws(IllegalArgumentException::class)
        set(value) {
            measurementsGenerator.baseNoiseLevelAbsoluteThreshold = value
        }

    /**
     * Gets or sets overall absolute threshold to determine whether there has been excessive motion
     * during the whole initialization phase. Failure will be detected if estimated base noise level
     * exceeds this threshold when initialization completes.
     *
     * @throws IllegalArgumentException if provided value is zero or negative.
     */
    override var baseNoiseLevelAbsoluteThresholdAsMeasurement: Acceleration
        get() = measurementsGenerator.baseNoiseLevelAbsoluteThresholdAsMeasurement
        @Throws(IllegalArgumentException::class)
        set(value) {
            measurementsGenerator.setBaseNoiseLevelAbsoluteThreshold(value)
        }

    /**
     * Gets overall absolute threshold to determine whether there has been excessive motion during
     * the whole initialization phase. Failure will be detected if estimated base noise level
     * exceeds this threshold when initialization completes.
     *
     * @param result instance where result will be stored.
     */
    override fun getBaseNoiseLevelAbsoluteThresholdAsMeasurement(result: Acceleration) {
        measurementsGenerator.getBaseNoiseLevelAbsoluteThresholdAsMeasurement(result)
    }

    /**
     * Gets accelerometer measurement base noise level that has been detected during initialization
     * expressed in meters per squared second (m/s^2).
     * This is only available once detector completes initialization.
     */
    override val accelerometerBaseNoiseLevel
        get() = if (initialized) {
            measurementsGenerator.accelerometerBaseNoiseLevel
        } else {
            null
        }

    /**
     * Gets accelerometer measurement base noise level that has been detected during initialization.
     * This is only available once detector completes initialization.
     */
    override val accelerometerBaseNoiseLevelAsMeasurement
        get() = if (initialized) {
            measurementsGenerator.accelerometerBaseNoiseLevelAsMeasurement
        } else {
            null
        }

    /**
     * Gets sensor measurement base noise level that has been detected during initialization.
     * This is only available once detector completes initialization.
     *
     * @param result instance where result will be stored.
     * @return true if result is available, false otherwise.
     */
    override fun getAccelerometerBaseNoiseLevelAsMeasurement(result: Acceleration): Boolean {
        return if (initialized) {
            measurementsGenerator.getAccelerometerBaseNoiseLevelAsMeasurement(result)
            true
        } else {
            false
        }
    }

    /**
     * Gets measurement base noise level PSD (Power Spectral Density) expressed in (m^2 * s^-3).
     */
    override val accelerometerBaseNoiseLevelPsd
        get() = if (initialized) {
            measurementsGenerator.accelerometerBaseNoiseLevelPsd
        } else {
            null
        }

    /**
     * Gets measurement base noise level root PSD (Power Spectral Density) expressed
     * in (m * s^-1.5).
     * This is only available once detector completes initialization.
     */
    override val accelerometerBaseNoiseLevelRootPsd
        get() = if (initialized) {
            measurementsGenerator.accelerometerBaseNoiseLevelRootPsd
        } else {
            null
        }

    /**
     * Gets estimated threshold to determine static/dynamic period changes expressed in meters per
     * squared second (m/s^2).
     * This is only available once detector completes initialization.
     */
    override val threshold
        get() = if (initialized) {
            measurementsGenerator.threshold
        } else {
            null
        }

    /**
     * Gets estimated threshold to determine static/dynamic period changes.
     * This is only available once detector completes initialization.
     */
    override val thresholdAsMeasurement
        get() = if (initialized) {
            measurementsGenerator.thresholdAsMeasurement
        } else {
            null
        }

    /**
     * Gets estimated threshold to determine static/dynamic period changes.
     * This is only available once detector completes initialization.
     *
     * @param result instance where result will be stored.
     * @return true if result is available, false otherwise.
     */
    override fun getThresholdAsMeasurement(result: Acceleration): Boolean {
        return if (initialized) {
            measurementsGenerator.getThresholdAsMeasurement(result)
            true
        } else {
            false
        }
    }

    /**
     * Gets number of samples that have been processed in a static period so far.
     */
    override val processedStaticSamples
        get() = measurementsGenerator.processedStaticSamples

    /**
     * Gets number of samples that have been processed in a dynamic period so far.
     */
    override val processedDynamicSamples
        get() = measurementsGenerator.processedDynamicSamples

    /**
     * Indicates whether last static interval must be skipped.
     */
    override val isStaticIntervalSkipped
        get() = measurementsGenerator.isStaticIntervalSkipped

    /**
     * Indicates whether last dynamic interval must be skipped.
     */
    override val isDynamicIntervalSkipped
        get() = measurementsGenerator.isDynamicIntervalSkipped

    /**
     * Gets status of measurement generator.
     * Initially the generator will be idle.
     * Once it starts, it will start the initialization phase, and once
     * initialization is complete, it will switch between static or dynamic interval
     * until generator is stopped or an error occurs.
     */
    override val status: Status
        get() = Status.mapStatus(measurementsGenerator.status, unreliable)

    /**
     * Resets generator to its initial state.
     */
    open fun reset() {
        accelerometerTimeIntervalEstimator.totalSamples = Integer.MAX_VALUE
        accelerometerTimeIntervalEstimator.reset()
        measurementsGenerator.reset()
        unreliable = false
        initialAccelerometerTimestamp = 0L
        numberOfProcessedAccelerometerMeasurements = 0
        initialized = false
    }

    /**
     * Interface to notify when processor's internal generator starts initialization.
     *
     * @param P an implementation of [SingleSensorCalibrationMeasurementGeneratorProcessor].
     */
    fun interface OnInitializationStartedListener<P : SingleSensorCalibrationMeasurementGeneratorProcessor<P, *, *, *, *>> {

        /**
         * Called when initial static period starts so that base noise level starts being estimated.
         *
         * @param processor processor that raised the event.
         */
        fun onInitializationStarted(processor: P)
    }

    /**
     * Interface to notify when processor's internal generator completes its initialization.
     *
     * @param P an implementation of [SingleSensorCalibrationMeasurementGeneratorProcessor].
     */
    fun interface OnInitializationCompletedListener<P : SingleSensorCalibrationMeasurementGeneratorProcessor<P, *, *, *, *>> {

        /**
         * Called when initial static period successfully completes and accelerometer base noise
         * level is estimated so that static and dynamic periods can be detected.
         *
         * @param processor processor that raised the event.
         * @param baseNoiseLevel base measurement noise level expressed in meters per squared second
         * (m/s^2).
         */
        fun onInitializationCompleted(processor: P, baseNoiseLevel: Double)
    }

    /**
     * Interface to notify when an error occurs.
     *
     * @param P an implementation of [SingleSensorCalibrationMeasurementGeneratorProcessor].
     */
    fun interface OnErrorListener<P : SingleSensorCalibrationMeasurementGeneratorProcessor<P, *, *, *, *>> {

        /**
         * Called when an error is detected, either at initialization because excessive changes in
         * sensor measurements are found, or because sensor becomes unreliable.
         * When an error occurs, processors' internal generator is stopped and needs to be restarted
         * to be used again.
         *
         * @param processor processor that raised the event.
         * @param reason reason for error.
         */
        fun onError(processor: P,reason: ErrorReason)
    }

    /**
     * Interface to notify that a new static interval is detected.
     *
     * @param P an implementation of [SingleSensorCalibrationMeasurementGeneratorProcessor].
     */
    fun interface OnStaticIntervalDetectedListener<P : SingleSensorCalibrationMeasurementGeneratorProcessor<P, *, *, *, *>> {

        /**
         * Called when a static interval has been detected after initialization.
         *
         * @param processor processor that raised the event.
         */
        fun onStaticIntervalDetected(processor: P)
    }

    /**
     * Interface to notify when a dynamic interval is detected.
     *
     * @param P an implementation of [SingleSensorCalibrationMeasurementGeneratorProcessor].
     */
    fun interface OnDynamicIntervalDetectedListener<P : SingleSensorCalibrationMeasurementGeneratorProcessor<P, *, *, *, *>> {

        /**
         * Called when a dynamic interval has been detected after initialization.
         *
         * @param processor processor that raised the event.
         */
        fun onDynamicIntervalDetected(processor: P)
    }

    /**
     * Interface to notify when a static interval is skipped.
     * This happens when interval is too short.
     *
     * @param P an implementation of [SingleSensorCalibrationMeasurementGeneratorProcessor].
     */
    fun interface OnStaticIntervalSkippedListener<P : SingleSensorCalibrationMeasurementGeneratorProcessor<P, *, *, *, *>> {

        /**
         * Called when a detected static interval is skipped because there are not enough samples to
         * be processed.
         *
         * @param processor processor that raised the event.
         */
        fun onStaticIntervalSkipped(processor: P)
    }

    /**
     * Interface to notify when a dynamic interval is skipped.
     * This happens when interval is too long.
     *
     * @param P an implementation of [SingleSensorCalibrationMeasurementGeneratorProcessor].
     */
    fun interface OnDynamicIntervalSkippedListener<P : SingleSensorCalibrationMeasurementGeneratorProcessor<P, *, *, *, *>> {

        /**
         * Called when a detected dynamic interval is skipped because it has too many samples in it.
         *
         * @param processor processor that raised the event.
         */
        fun onDynamicIntervalSkipped(processor: P)
    }

    /**
     * Interface to notify when a new calibration measurement is generated.
     *
     * @param P an implementation of [SingleSensorCalibrationMeasurementGeneratorProcessor].
     * @param T type of measurement to be generated.
     */
    fun interface OnGeneratedMeasurementListener<P : SingleSensorCalibrationMeasurementGeneratorProcessor<P, T, *, *, *>, T> {

        /**
         * Called when a new calibration measurement is generated.
         *
         * @param processor processor that raised the event.
         * @param measurement generated calibration measurement.
         */
        fun onGeneratedMeasurement(processor: P, measurement: T)
    }

    /**
     * Interface to notify when generator is reset (occurs when starting after stopping the
     * generator)
     *
     * @param P an implementation of [SingleSensorCalibrationMeasurementGeneratorProcessor].
     */
    fun interface OnResetListener<P : SingleSensorCalibrationMeasurementGeneratorProcessor<P, *, *, *, *>> {
        /**
         * Called when processor is reset.
         *
         * @param processor processor that raised the event.
         */
        fun onReset(processor: P)
    }
}